export interface DeviceTemplate {
  id: string;
  name: string;
  type: string;
  category:
    | "router"
    | "switch"
    | "firewall"
    | "access-point"
    | "server"
    | "nas"
    | "camera"
    | "client"
    | "cloud";
  vendor: string;
  description: string;
  portCount?: number;
  bandwidth?: string;
  powerConsumption?: string;
  rackUnits?: number;
  defaultVLAN?: number;
  tags?: string[];
  metadata?: {
    Layer?: "2" | "3";
    "PoE Budget"?: string;
    Capabilities?: string;
    "SFP+ Ports"?: string;
    Throughput?: string;
    "Max VLANs"?: string;
    Coverage?: string;
    Standard?: string;
    Resolution?: string;
    Storage?: string;
    NICs?: string;
    CPUs?: string;
    RAM?: string;
    "Drive Bays"?: string;
  };
}

export const DEVICE_TEMPLATES: DeviceTemplate[] = [
  // ROUTERS
  {
    id: "cisco-isr-4331",
    name: "Cisco ISR 4331",
    type: "router",
    category: "router",
    vendor: "Cisco",
    description: "Enterprise branch router with integrated services",
    portCount: 4,
    bandwidth: "2 Gbps",
    powerConsumption: "150W",
    rackUnits: 1,
    tags: ["enterprise", "branch", "layer3"],
    metadata: {
      Layer: "3",
      Capabilities: "Routing, NAT, VPN, QoS, Firewall",
      Throughput: "2 Gbps",
      "Max VLANs": "4096",
    },
  },
  {
    id: "cisco-isr-4451",
    name: "Cisco ISR 4451",
    type: "router",
    category: "router",
    vendor: "Cisco",
    description: "High-performance enterprise router",
    portCount: 4,
    bandwidth: "5 Gbps",
    powerConsumption: "250W",
    rackUnits: 1,
    tags: ["enterprise", "high-performance", "layer3"],
    metadata: {
      Layer: "3",
      Capabilities: "Routing, NAT, VPN, QoS, Advanced Security",
      Throughput: "5 Gbps",
      "Max VLANs": "4096",
    },
  },
  {
    id: "unifi-udm-pro",
    name: "UniFi Dream Machine Pro",
    type: "router",
    category: "router",
    vendor: "Ubiquiti",
    description: "All-in-one router, switch, and controller",
    portCount: 10,
    bandwidth: "3.5 Gbps",
    powerConsumption: "26W",
    rackUnits: 1,
    tags: ["prosumer", "all-in-one", "layer3"],
    metadata: {
      Layer: "3",
      Capabilities: "Routing, NAT, VPN, IDS/IPS, DPI",
      "SFP+ Ports": "2",
      Throughput: "3.5 Gbps",
      "Max VLANs": "32",
    },
  },
  {
    id: "unifi-udm-se",
    name: "UniFi Dream Machine SE",
    type: "router",
    category: "router",
    vendor: "Ubiquiti",
    description: "Enhanced UDM with PoE and storage",
    portCount: 10,
    bandwidth: "3.5 Gbps",
    powerConsumption: "60W",
    rackUnits: 0,
    tags: ["prosumer", "poe", "layer3"],
    metadata: {
      Layer: "3",
      Capabilities: "Routing, NAT, VPN, IDS/IPS, PoE+",
      "PoE Budget": "100W",
      "SFP+ Ports": "1",
      Throughput: "3.5 Gbps",
      "Max VLANs": "32",
    },
  },
  {
    id: "mikrotik-rb5009",
    name: "MikroTik RB5009UG+S+IN",
    type: "router",
    category: "router",
    vendor: "MikroTik",
    description: "Multi-gigabit router with SFP+",
    portCount: 9,
    bandwidth: "10 Gbps",
    powerConsumption: "30W",
    rackUnits: 0,
    tags: ["prosumer", "high-performance", "layer3"],
    metadata: {
      Layer: "3",
      Capabilities: "Routing, NAT, VPN, MPLS, BGP",
      "SFP+ Ports": "1",
      Throughput: "10 Gbps",
      "Max VLANs": "4096",
    },
  },
  {
    id: "mikrotik-ccr2004",
    name: "MikroTik CCR2004-16G-2S+",
    type: "router",
    category: "router",
    vendor: "MikroTik",
    description: "Cloud core router for demanding networks",
    portCount: 18,
    bandwidth: "16 Gbps",
    powerConsumption: "55W",
    rackUnits: 1,
    tags: ["enterprise", "carrier-grade", "layer3"],
    metadata: {
      Layer: "3",
      Capabilities: "Routing, BGP, MPLS, VPLS, QoS",
      "SFP+ Ports": "2",
      Throughput: "16 Gbps",
      "Max VLANs": "4096",
    },
  },
  {
    id: "edgerouter-4",
    name: "EdgeRouter 4",
    type: "router",
    category: "router",
    vendor: "Ubiquiti",
    description: "Advanced routing for small business",
    portCount: 4,
    bandwidth: "4 Gbps",
    powerConsumption: "18W",
    rackUnits: 0,
    tags: ["smb", "layer3", "budget"],
    metadata: {
      Layer: "3",
      Capabilities: "Routing, NAT, VPN, QoS",
      Throughput: "4 Gbps",
      "Max VLANs": "4096",
    },
  },
  {
    id: "pfsense-router",
    name: "pfSense Router",
    type: "router",
    category: "router",
    vendor: "Netgate",
    description: "Open-source router/firewall platform",
    portCount: 4,
    bandwidth: "10 Gbps",
    powerConsumption: "65W",
    rackUnits: 1,
    tags: ["open-source", "layer3", "firewall"],
    metadata: {
      Layer: "3",
      Capabilities: "Routing, NAT, VPN, Firewall, IDS/IPS",
      Throughput: "10 Gbps",
      "Max VLANs": "Unlimited",
    },
  },

  // SWITCHES
  {
    id: "cisco-2960x-24ps",
    name: "Cisco Catalyst 2960X-24PS",
    type: "switch",
    category: "switch",
    vendor: "Cisco",
    description: "24-port PoE+ managed switch",
    portCount: 28,
    bandwidth: "52 Gbps",
    powerConsumption: "370W",
    rackUnits: 1,
    tags: ["enterprise", "poe", "layer2"],
    metadata: {
      Layer: "2",
      "PoE Budget": "370W",
      Capabilities: "Layer 2 switching, PoE+, VLAN",
      "SFP+ Ports": "4",
      "Max VLANs": "4096",
    },
  },
  {
    id: "cisco-2960x-48fps",
    name: "Cisco Catalyst 2960X-48FPS",
    type: "switch",
    category: "switch",
    vendor: "Cisco",
    description: "48-port PoE+ full-power switch",
    portCount: 52,
    bandwidth: "176 Gbps",
    powerConsumption: "740W",
    rackUnits: 1,
    tags: ["enterprise", "poe", "layer2"],
    metadata: {
      Layer: "2",
      "PoE Budget": "740W",
      Capabilities: "Layer 2 switching, PoE+, VLAN",
      "SFP+ Ports": "4",
      "Max VLANs": "4096",
    },
  },
  {
    id: "cisco-3850-24p",
    name: "Cisco Catalyst 3850-24P",
    type: "switch",
    category: "switch",
    vendor: "Cisco",
    description: "Layer 3 stackable switch with PoE+",
    portCount: 28,
    bandwidth: "88 Gbps",
    powerConsumption: "495W",
    rackUnits: 1,
    tags: ["enterprise", "poe", "layer3", "stackable"],
    metadata: {
      Layer: "3",
      "PoE Budget": "495W",
      Capabilities: "Layer 3 routing, PoE+, Stacking, VLAN",
      "SFP+ Ports": "4",
      Throughput: "88 Gbps",
      "Max VLANs": "4096",
    },
  },
  {
    id: "cisco-9300-24p",
    name: "Cisco Catalyst 9300-24P",
    type: "switch",
    category: "switch",
    vendor: "Cisco",
    description: "Next-gen enterprise switch with PoE+",
    portCount: 28,
    bandwidth: "208 Gbps",
    powerConsumption: "495W",
    rackUnits: 1,
    tags: ["enterprise", "poe", "layer3", "next-gen"],
    metadata: {
      Layer: "3",
      "PoE Budget": "495W",
      Capabilities: "Layer 3 routing, PoE+, StackWise, DNA",
      "SFP+ Ports": "4",
      Throughput: "208 Gbps",
      "Max VLANs": "4096",
    },
  },
  {
    id: "cisco-9300-48p",
    name: "Cisco Catalyst 9300-48P",
    type: "switch",
    category: "switch",
    vendor: "Cisco",
    description: "48-port next-gen enterprise switch",
    portCount: 52,
    bandwidth: "440 Gbps",
    powerConsumption: "715W",
    rackUnits: 1,
    tags: ["enterprise", "poe", "layer3", "high-density"],
    metadata: {
      Layer: "3",
      "PoE Budget": "715W",
      Capabilities: "Layer 3 routing, PoE+, StackWise, DNA",
      "SFP+ Ports": "4",
      Throughput: "440 Gbps",
      "Max VLANs": "4096",
    },
  },
  {
    id: "unifi-us-24",
    name: "UniFi Switch 24",
    type: "switch",
    category: "switch",
    vendor: "Ubiquiti",
    description: "24-port managed switch",
    portCount: 26,
    bandwidth: "52 Gbps",
    powerConsumption: "20W",
    rackUnits: 1,
    tags: ["prosumer", "layer2", "budget"],
    metadata: {
      Layer: "2",
      Capabilities: "Layer 2 switching, VLAN",
      "SFP+ Ports": "2",
      "Max VLANs": "128",
    },
  },
  {
    id: "unifi-us-24-poe",
    name: "UniFi Switch 24 PoE",
    type: "switch",
    category: "switch",
    vendor: "Ubiquiti",
    description: "24-port PoE+ managed switch",
    portCount: 26,
    bandwidth: "52 Gbps",
    powerConsumption: "250W",
    rackUnits: 1,
    tags: ["prosumer", "poe", "layer2"],
    metadata: {
      Layer: "2",
      "PoE Budget": "250W",
      Capabilities: "Layer 2 switching, PoE+, VLAN",
      "SFP+ Ports": "2",
      "Max VLANs": "128",
    },
  },
  {
    id: "unifi-us-48-pro",
    name: "UniFi Switch 48 Pro",
    type: "switch",
    category: "switch",
    vendor: "Ubiquiti",
    description: "48-port PoE+ pro switch",
    portCount: 52,
    bandwidth: "104 Gbps",
    powerConsumption: "250W",
    rackUnits: 1,
    tags: ["prosumer", "poe", "layer2"],
    metadata: {
      Layer: "2",
      "PoE Budget": "250W",
      Capabilities: "Layer 2 switching, PoE+, VLAN",
      "SFP+ Ports": "4",
      "Max VLANs": "128",
    },
  },
  {
    id: "unifi-aggregation",
    name: "UniFi Switch Aggregation",
    type: "switch",
    category: "switch",
    vendor: "Ubiquiti",
    description: "High-performance aggregation switch",
    portCount: 28,
    bandwidth: "320 Gbps",
    powerConsumption: "40W",
    rackUnits: 1,
    tags: ["prosumer", "layer3", "aggregation"],
    metadata: {
      Layer: "3",
      Capabilities: "Layer 3 routing, SFP+, VLAN",
      "SFP+ Ports": "8",
      Throughput: "320 Gbps",
      "Max VLANs": "128",
    },
  },
  {
    id: "meraki-ms120-24p",
    name: "Cisco Meraki MS120-24P",
    type: "switch",
    category: "switch",
    vendor: "Cisco",
    description: "Cloud-managed 24-port PoE+ switch",
    portCount: 24,
    bandwidth: "48 Gbps",
    powerConsumption: "370W",
    rackUnits: 1,
    tags: ["cloud-managed", "poe", "layer2"],
    metadata: {
      Layer: "2",
      "PoE Budget": "370W",
      Capabilities: "Cloud management, PoE+, VLAN",
      "Max VLANs": "512",
    },
  },
  {
    id: "meraki-ms225-48fp",
    name: "Cisco Meraki MS225-48FP",
    type: "switch",
    category: "switch",
    vendor: "Cisco",
    description: "Cloud-managed 48-port full PoE switch",
    portCount: 52,
    bandwidth: "176 Gbps",
    powerConsumption: "740W",
    rackUnits: 1,
    tags: ["cloud-managed", "poe", "layer3"],
    metadata: {
      Layer: "3",
      "PoE Budget": "740W",
      Capabilities: "Cloud management, Layer 3, PoE+",
      "SFP+ Ports": "4",
      Throughput: "176 Gbps",
      "Max VLANs": "4096",
    },
  },
  {
    id: "netgear-gs724tp",
    name: "Netgear GS724TP",
    type: "switch",
    category: "switch",
    vendor: "Netgear",
    description: "24-port PoE+ smart switch",
    portCount: 24,
    bandwidth: "48 Gbps",
    powerConsumption: "190W",
    rackUnits: 1,
    tags: ["smb", "poe", "layer2", "budget"],
    metadata: {
      Layer: "2",
      "PoE Budget": "190W",
      Capabilities: "Layer 2 switching, PoE+, VLAN",
      "Max VLANs": "256",
    },
  },
  {
    id: "aruba-2930f-24g",
    name: "Aruba 2930F 24G",
    type: "switch",
    category: "switch",
    vendor: "Aruba",
    description: "Enterprise 24-port PoE+ switch",
    portCount: 28,
    bandwidth: "128 Gbps",
    powerConsumption: "370W",
    rackUnits: 1,
    tags: ["enterprise", "poe", "layer3"],
    metadata: {
      Layer: "3",
      "PoE Budget": "370W",
      Capabilities: "Layer 3 routing, PoE+, Stacking",
      "SFP+ Ports": "4",
      Throughput: "128 Gbps",
      "Max VLANs": "4096",
    },
  },
  {
    id: "aruba-cx6300-24p",
    name: "Aruba CX 6300 24-port",
    type: "switch",
    category: "switch",
    vendor: "Aruba",
    description: "Next-gen campus switch",
    portCount: 28,
    bandwidth: "208 Gbps",
    powerConsumption: "495W",
    rackUnits: 1,
    tags: ["enterprise", "poe", "layer3", "next-gen"],
    metadata: {
      Layer: "3",
      "PoE Budget": "495W",
      Capabilities: "Layer 3, VSF stacking, PoE+",
      "SFP+ Ports": "4",
      Throughput: "208 Gbps",
      "Max VLANs": "4096",
    },
  },
  {
    id: "juniper-ex2300-24p",
    name: "Juniper EX2300-24P",
    type: "switch",
    category: "switch",
    vendor: "Juniper",
    description: "Compact enterprise PoE+ switch",
    portCount: 28,
    bandwidth: "56 Gbps",
    powerConsumption: "370W",
    rackUnits: 1,
    tags: ["enterprise", "poe", "layer2"],
    metadata: {
      Layer: "2",
      "PoE Budget": "370W",
      Capabilities: "Layer 2 switching, PoE+, VLAN",
      "SFP+ Ports": "4",
      "Max VLANs": "4096",
    },
  },
  {
    id: "tp-link-t2600g",
    name: "TP-Link T2600G-28TS",
    type: "switch",
    category: "switch",
    vendor: "TP-Link",
    description: "Budget 28-port managed switch",
    portCount: 28,
    bandwidth: "56 Gbps",
    powerConsumption: "38W",
    rackUnits: 1,
    tags: ["budget", "layer2", "smb"],
    metadata: {
      Layer: "2",
      Capabilities: "Layer 2 switching, VLAN",
      "SFP+ Ports": "4",
      "Max VLANs": "256",
    },
  },

  // FIREWALLS
  {
    id: "palo-alto-pa-220",
    name: "Palo Alto PA-220",
    type: "firewall",
    category: "firewall",
    vendor: "Palo Alto",
    description: "Next-gen firewall for small branch",
    portCount: 8,
    bandwidth: "900 Mbps",
    powerConsumption: "30W",
    rackUnits: 0,
    tags: ["ngfw", "branch", "enterprise"],
    metadata: {
      Layer: "3",
      Capabilities: "NGFW, IPS, URL filtering, App-ID",
      Throughput: "900 Mbps",
      "Max VLANs": "1024",
    },
  },
  {
    id: "palo-alto-pa-850",
    name: "Palo Alto PA-850",
    type: "firewall",
    category: "firewall",
    vendor: "Palo Alto",
    description: "High-performance next-gen firewall",
    portCount: 16,
    bandwidth: "3 Gbps",
    powerConsumption: "120W",
    rackUnits: 1,
    tags: ["ngfw", "enterprise", "high-performance"],
    metadata: {
      Layer: "3",
      Capabilities: "NGFW, Advanced IPS, Threat Prevention",
      "SFP+ Ports": "4",
      Throughput: "3 Gbps",
      "Max VLANs": "4096",
    },
  },
  {
    id: "fortigate-60e",
    name: "FortiGate 60E",
    type: "firewall",
    category: "firewall",
    vendor: "Fortinet",
    description: "Compact UTM firewall",
    portCount: 10,
    bandwidth: "3 Gbps",
    powerConsumption: "21W",
    rackUnits: 0,
    tags: ["utm", "smb", "ngfw"],
    metadata: {
      Layer: "3",
      Capabilities: "UTM, IPS, Antivirus, Web filtering",
      Throughput: "3 Gbps",
      "Max VLANs": "512",
    },
  },
  {
    id: "fortigate-100f",
    name: "FortiGate 100F",
    type: "firewall",
    category: "firewall",
    vendor: "Fortinet",
    description: "Enterprise security appliance",
    portCount: 18,
    bandwidth: "10 Gbps",
    powerConsumption: "60W",
    rackUnits: 1,
    tags: ["ngfw", "enterprise", "utm"],
    metadata: {
      Layer: "3",
      Capabilities: "NGFW, Advanced Threats, SD-WAN",
      "SFP+ Ports": "2",
      Throughput: "10 Gbps",
      "Max VLANs": "4096",
    },
  },
  {
    id: "sophos-xg-85",
    name: "Sophos XG 85",
    type: "firewall",
    category: "firewall",
    vendor: "Sophos",
    description: "Desktop firewall appliance",
    portCount: 4,
    bandwidth: "1.1 Gbps",
    powerConsumption: "40W",
    rackUnits: 0,
    tags: ["utm", "smb", "desktop"],
    metadata: {
      Layer: "3",
      Capabilities: "UTM, IPS, Web protection, Email security",
      Throughput: "1.1 Gbps",
      "Max VLANs": "256",
    },
  },
  {
    id: "sophos-xg-210",
    name: "Sophos XG 210",
    type: "firewall",
    category: "firewall",
    vendor: "Sophos",
    description: "Rackmount enterprise firewall",
    portCount: 8,
    bandwidth: "3.5 Gbps",
    powerConsumption: "90W",
    rackUnits: 1,
    tags: ["utm", "enterprise", "ngfw"],
    metadata: {
      Layer: "3",
      Capabilities: "NGFW, Synchronized Security, SD-WAN",
      "SFP+ Ports": "2",
      Throughput: "3.5 Gbps",
      "Max VLANs": "512",
    },
  },
  {
    id: "watchguard-t35",
    name: "WatchGuard Firebox T35",
    type: "firewall",
    category: "firewall",
    vendor: "WatchGuard",
    description: "SMB tabletop firewall",
    portCount: 5,
    bandwidth: "940 Mbps",
    powerConsumption: "25W",
    rackUnits: 0,
    tags: ["utm", "smb", "desktop"],
    metadata: {
      Layer: "3",
      Capabilities: "UTM, IPS, Gateway AV, APT Blocker",
      Throughput: "940 Mbps",
      "Max VLANs": "256",
    },
  },
  {
    id: "opnsense-firewall",
    name: "OPNsense Firewall",
    type: "firewall",
    category: "firewall",
    vendor: "OPNsense",
    description: "Open-source firewall platform",
    portCount: 6,
    bandwidth: "10 Gbps",
    powerConsumption: "75W",
    rackUnits: 1,
    tags: ["open-source", "utm", "ngfw"],
    metadata: {
      Layer: "3",
      Capabilities: "Firewall, VPN, IDS/IPS, Proxy",
      Throughput: "10 Gbps",
      "Max VLANs": "Unlimited",
    },
  },

  // ACCESS POINTS
  {
    id: "unifi-u6-pro",
    name: "UniFi U6 Pro",
    type: "access-point",
    category: "access-point",
    vendor: "Ubiquiti",
    description: "WiFi 6 dual-band access point",
    portCount: 1,
    bandwidth: "5.3 Gbps",
    powerConsumption: "16W",
    tags: ["wifi6", "prosumer", "indoor"],
    metadata: {
      Standard: "WiFi 6 (802.11ax)",
      Coverage: "140m²",
      Capabilities: "Dual-band, MU-MIMO, OFDMA",
    },
  },
  {
    id: "unifi-u6-enterprise",
    name: "UniFi U6 Enterprise",
    type: "access-point",
    category: "access-point",
    vendor: "Ubiquiti",
    description: "WiFi 6 tri-band enterprise AP",
    portCount: 1,
    bandwidth: "7.2 Gbps",
    powerConsumption: "20W",
    tags: ["wifi6", "enterprise", "tri-band"],
    metadata: {
      Standard: "WiFi 6 (802.11ax)",
      Coverage: "185m²",
      Capabilities: "Tri-band, 160MHz, 4x4 MU-MIMO",
    },
  },
  {
    id: "unifi-u6-lite",
    name: "UniFi U6 Lite",
    type: "access-point",
    category: "access-point",
    vendor: "Ubiquiti",
    description: "Budget WiFi 6 access point",
    portCount: 1,
    bandwidth: "1.5 Gbps",
    powerConsumption: "12W",
    tags: ["wifi6", "budget", "indoor"],
    metadata: {
      Standard: "WiFi 6 (802.11ax)",
      Coverage: "93m²",
      Capabilities: "Dual-band, MU-MIMO",
    },
  },
  {
    id: "unifi-u6-lr",
    name: "UniFi U6 LR",
    type: "access-point",
    category: "access-point",
    vendor: "Ubiquiti",
    description: "WiFi 6 long-range access point",
    portCount: 1,
    bandwidth: "3 Gbps",
    powerConsumption: "16W",
    tags: ["wifi6", "long-range", "outdoor"],
    metadata: {
      Standard: "WiFi 6 (802.11ax)",
      Coverage: "185m²",
      Capabilities: "Dual-band, Long-range, Outdoor",
    },
  },
  {
    id: "cisco-9120axi",
    name: "Cisco Catalyst 9120AXI",
    type: "access-point",
    category: "access-point",
    vendor: "Cisco",
    description: "Enterprise WiFi 6 indoor AP",
    portCount: 1,
    bandwidth: "5.2 Gbps",
    powerConsumption: "30W",
    tags: ["wifi6", "enterprise", "indoor"],
    metadata: {
      Standard: "WiFi 6 (802.11ax)",
      Coverage: "150m²",
      Capabilities: "Dual-band, 4x4 MU-MIMO, DNA",
    },
  },
  {
    id: "cisco-9136i",
    name: "Cisco Catalyst 9136I",
    type: "access-point",
    category: "access-point",
    vendor: "Cisco",
    description: "High-density WiFi 6E AP",
    portCount: 1,
    bandwidth: "10.7 Gbps",
    powerConsumption: "35W",
    tags: ["wifi6e", "enterprise", "high-density"],
    metadata: {
      Standard: "WiFi 6E (802.11ax)",
      Coverage: "185m²",
      Capabilities: "Tri-band, 6GHz, 8x8 MU-MIMO",
    },
  },
  {
    id: "aruba-ap-515",
    name: "Aruba AP-515",
    type: "access-point",
    category: "access-point",
    vendor: "Aruba",
    description: "Enterprise WiFi 6 access point",
    portCount: 1,
    bandwidth: "5.4 Gbps",
    powerConsumption: "25W",
    tags: ["wifi6", "enterprise", "indoor"],
    metadata: {
      Standard: "WiFi 6 (802.11ax)",
      Coverage: "140m²",
      Capabilities: "Dual-band, 4x4 MU-MIMO, OFDMA",
    },
  },
  {
    id: "aruba-ap-635",
    name: "Aruba AP-635",
    type: "access-point",
    category: "access-point",
    vendor: "Aruba",
    description: "High-performance WiFi 6E AP",
    portCount: 1,
    bandwidth: "10.8 Gbps",
    powerConsumption: "30W",
    tags: ["wifi6e", "enterprise", "tri-band"],
    metadata: {
      Standard: "WiFi 6E (802.11ax)",
      Coverage: "185m²",
      Capabilities: "Tri-band, 6GHz, 4x4 MU-MIMO",
    },
  },
  {
    id: "ruckus-r750",
    name: "Ruckus R750",
    type: "access-point",
    category: "access-point",
    vendor: "Ruckus",
    description: "Premium WiFi 6 enterprise AP",
    portCount: 1,
    bandwidth: "6 Gbps",
    powerConsumption: "28W",
    tags: ["wifi6", "enterprise", "premium"],
    metadata: {
      Standard: "WiFi 6 (802.11ax)",
      Coverage: "160m²",
      Capabilities: "Dual-band, 8x8 MU-MIMO, BeamFlex",
    },
  },

  // SERVERS
  {
    id: "dell-r640",
    name: "Dell PowerEdge R640",
    type: "server",
    category: "server",
    vendor: "Dell",
    description: "1U dual-processor server",
    portCount: 4,
    bandwidth: "10 Gbps",
    powerConsumption: "750W",
    rackUnits: 1,
    tags: ["enterprise", "rackmount", "virtualization"],
    metadata: {
      CPUs: "2x Intel Xeon Scalable",
      RAM: "Up to 3TB DDR4",
      "Drive Bays": '10x 2.5"',
      NICs: "4x 1GbE",
    },
  },
  {
    id: "dell-r740xd",
    name: "Dell PowerEdge R740xd",
    type: "server",
    category: "server",
    vendor: "Dell",
    description: "2U high-capacity storage server",
    portCount: 4,
    bandwidth: "10 Gbps",
    powerConsumption: "1100W",
    rackUnits: 2,
    tags: ["enterprise", "storage", "rackmount"],
    metadata: {
      CPUs: "2x Intel Xeon Scalable",
      RAM: "Up to 3TB DDR4",
      "Drive Bays": '24x 2.5" or 12x 3.5"',
      NICs: "4x 1GbE",
    },
  },
  {
    id: "hpe-dl360-gen10",
    name: "HPE ProLiant DL360 Gen10",
    type: "server",
    category: "server",
    vendor: "HPE",
    description: "1U versatile rack server",
    portCount: 4,
    bandwidth: "10 Gbps",
    powerConsumption: "800W",
    rackUnits: 1,
    tags: ["enterprise", "rackmount", "general-purpose"],
    metadata: {
      CPUs: "2x Intel Xeon Scalable",
      RAM: "Up to 3TB DDR4",
      "Drive Bays": '10x 2.5"',
      NICs: "4x 1GbE",
    },
  },
  {
    id: "hpe-dl380-gen10",
    name: "HPE ProLiant DL380 Gen10",
    type: "server",
    category: "server",
    vendor: "HPE",
    description: "2U scalable server platform",
    portCount: 4,
    bandwidth: "10 Gbps",
    powerConsumption: "1600W",
    rackUnits: 2,
    tags: ["enterprise", "rackmount", "scalable"],
    metadata: {
      CPUs: "2x Intel Xeon Scalable",
      RAM: "Up to 3TB DDR4",
      "Drive Bays": '24x 2.5" or 12x 3.5"',
      NICs: "4x 1GbE",
    },
  },
  {
    id: "supermicro-6029p",
    name: "Supermicro 6029P-TRT",
    type: "server",
    category: "server",
    vendor: "Supermicro",
    description: "2U twin server for virtualization",
    portCount: 4,
    bandwidth: "10 Gbps",
    powerConsumption: "1200W",
    rackUnits: 2,
    tags: ["enterprise", "virtualization", "high-density"],
    metadata: {
      CPUs: "4x Intel Xeon Scalable",
      RAM: "Up to 6TB DDR4",
      "Drive Bays": '24x 2.5" hot-swap',
      NICs: "8x 1GbE",
    },
  },
  {
    id: "supermicro-5019p",
    name: "Supermicro 5019P-MT",
    type: "server",
    category: "server",
    vendor: "Supermicro",
    description: "1U micro-tower server",
    portCount: 2,
    bandwidth: "1 Gbps",
    powerConsumption: "350W",
    rackUnits: 0,
    tags: ["smb", "tower", "budget"],
    metadata: {
      CPUs: "1x Intel Xeon",
      RAM: "Up to 256GB DDR4",
      "Drive Bays": '4x 3.5"',
      NICs: "2x 1GbE",
    },
  },

  // NAS
  {
    id: "synology-rs2421",
    name: "Synology RackStation RS2421+",
    type: "nas",
    category: "nas",
    vendor: "Synology",
    description: "12-bay rackmount NAS",
    portCount: 4,
    bandwidth: "1 Gbps",
    powerConsumption: "186W",
    rackUnits: 2,
    tags: ["nas", "rackmount", "prosumer"],
    metadata: {
      "Drive Bays": '12x 3.5"/2.5"',
      NICs: "4x 1GbE",
      Storage: "Up to 192TB",
      Capabilities: "iSCSI, Snapshots, Replication",
    },
  },
  {
    id: "synology-rs4021xs",
    name: "Synology RackStation RS4021xs+",
    type: "nas",
    category: "nas",
    vendor: "Synology",
    description: "High-performance 16-bay NAS",
    portCount: 4,
    bandwidth: "10 Gbps",
    powerConsumption: "314W",
    rackUnits: 3,
    tags: ["nas", "rackmount", "enterprise"],
    metadata: {
      "Drive Bays": '16x 3.5"/2.5"',
      NICs: "4x 1GbE, 2x 10GbE",
      Storage: "Up to 256TB",
      Capabilities: "SSD cache, HA, iSCSI, Snapshots",
    },
  },
  {
    id: "qnap-ts-h1283xu",
    name: "QNAP TS-h1283XU-RP",
    type: "nas",
    category: "nas",
    vendor: "QNAP",
    description: "Hybrid 12-bay rackmount NAS",
    portCount: 4,
    bandwidth: "10 Gbps",
    powerConsumption: "250W",
    rackUnits: 2,
    tags: ["nas", "rackmount", "hybrid"],
    metadata: {
      "Drive Bays": '12x 3.5" + 4x 2.5" SSD',
      NICs: "4x 2.5GbE",
      Storage: "Up to 192TB",
      Capabilities: "QuTS hero, ZFS, SSD cache",
    },
  },
  {
    id: "qnap-ts-2477xu",
    name: "QNAP TS-2477XU-RP",
    type: "nas",
    category: "nas",
    vendor: "QNAP",
    description: "Enterprise 24-bay rackmount NAS",
    portCount: 4,
    bandwidth: "10 Gbps",
    powerConsumption: "350W",
    rackUnits: 2,
    tags: ["nas", "rackmount", "enterprise"],
    metadata: {
      "Drive Bays": '24x 2.5"',
      NICs: "2x 10GbE SFP+",
      Storage: "Up to 384TB",
      Capabilities: "SSD optimization, Snapshots, HA",
    },
  },
  {
    id: "truenas-mini-x",
    name: "TrueNAS Mini X+",
    type: "nas",
    category: "nas",
    vendor: "iXsystems",
    description: "Compact 8-bay ZFS storage",
    portCount: 2,
    bandwidth: "10 Gbps",
    powerConsumption: "150W",
    rackUnits: 0,
    tags: ["nas", "desktop", "zfs"],
    metadata: {
      "Drive Bays": '8x 3.5"',
      NICs: "2x 10GbE",
      Storage: "Up to 128TB",
      Capabilities: "ZFS, Snapshots, Replication",
    },
  },

  // CAMERAS
  {
    id: "unifi-g4-pro",
    name: "UniFi G4 Pro",
    type: "camera",
    category: "camera",
    vendor: "Ubiquiti",
    description: "4K turret camera",
    portCount: 1,
    powerConsumption: "12W",
    tags: ["security", "poe", "4k"],
    metadata: {
      Resolution: "4K (3840x2160)",
      Capabilities: "HDR, WDR, IR night vision",
    },
  },
  {
    id: "unifi-g4-bullet",
    name: "UniFi G4 Bullet",
    type: "camera",
    category: "camera",
    vendor: "Ubiquiti",
    description: "2K bullet camera",
    portCount: 1,
    powerConsumption: "6W",
    tags: ["security", "poe", "outdoor"],
    metadata: {
      Resolution: "2K (2688x1520)",
      Capabilities: "IR night vision, Weatherproof",
    },
  },
  {
    id: "unifi-g4-dome",
    name: "UniFi G4 Dome",
    type: "camera",
    category: "camera",
    vendor: "Ubiquiti",
    description: "2K dome camera",
    portCount: 1,
    powerConsumption: "5W",
    tags: ["security", "poe", "indoor"],
    metadata: {
      Resolution: "2K (2688x1520)",
      Capabilities: "IR night vision, Vandal-resistant",
    },
  },
  {
    id: "axis-m3065-v",
    name: "Axis M3065-V",
    type: "camera",
    category: "camera",
    vendor: "Axis",
    description: "Fixed mini dome camera",
    portCount: 1,
    powerConsumption: "4W",
    tags: ["security", "poe", "compact"],
    metadata: {
      Resolution: "1080p (1920x1080)",
      Capabilities: "WDR, Edge storage, Audio",
    },
  },
  {
    id: "axis-p3265-lve",
    name: "Axis P3265-LVE",
    type: "camera",
    category: "camera",
    vendor: "Axis",
    description: "Outdoor dome camera",
    portCount: 1,
    powerConsumption: "14W",
    tags: ["security", "poe", "outdoor"],
    metadata: {
      Resolution: "1080p (1920x1080)",
      Capabilities: "IR, Lightfinder, Weatherproof",
    },
  },
  {
    id: "hikvision-ds-2cd2143g2",
    name: "Hikvision DS-2CD2143G2-I",
    type: "camera",
    category: "camera",
    vendor: "Hikvision",
    description: "4MP turret camera",
    portCount: 1,
    powerConsumption: "7W",
    tags: ["security", "poe", "ai"],
    metadata: {
      Resolution: "4MP (2560x1440)",
      Capabilities: "AcuSense, IR, H.265+",
    },
  },

  // CLIENTS
  {
    id: "desktop-pc",
    name: "Desktop PC",
    type: "client",
    category: "client",
    vendor: "Generic",
    description: "Standard desktop computer",
    portCount: 1,
    bandwidth: "1 Gbps",
    powerConsumption: "150W",
    tags: ["client", "workstation"],
    metadata: {
      NICs: "1x 1GbE",
      Capabilities: "General computing",
    },
  },
  {
    id: "laptop",
    name: "Laptop",
    type: "client",
    category: "client",
    vendor: "Generic",
    description: "Mobile laptop computer",
    portCount: 1,
    bandwidth: "1 Gbps",
    powerConsumption: "65W",
    tags: ["client", "mobile"],
    metadata: {
      NICs: "1x WiFi/1GbE",
      Capabilities: "Mobile computing",
    },
  },
  {
    id: "thin-client",
    name: "Thin Client",
    type: "client",
    category: "client",
    vendor: "Generic",
    description: "Virtual desktop endpoint",
    portCount: 1,
    bandwidth: "1 Gbps",
    powerConsumption: "15W",
    tags: ["client", "vdi"],
    metadata: {
      NICs: "1x 1GbE",
      Capabilities: "VDI, Remote desktop",
    },
  },
  {
    id: "voip-phone",
    name: "VoIP Phone",
    type: "client",
    category: "client",
    vendor: "Generic",
    description: "IP telephone",
    portCount: 2,
    bandwidth: "100 Mbps",
    powerConsumption: "5W",
    tags: ["client", "voip", "poe"],
    metadata: {
      NICs: "2x 100Mbps (passthrough)",
      Capabilities: "Voice, PoE powered",
    },
  },
  {
    id: "iot-device",
    name: "IoT Device",
    type: "client",
    category: "client",
    vendor: "Generic",
    description: "Generic IoT endpoint",
    portCount: 1,
    bandwidth: "100 Mbps",
    powerConsumption: "3W",
    tags: ["client", "iot"],
    metadata: {
      NICs: "1x WiFi/Ethernet",
      Capabilities: "Automation, Sensors",
    },
  },

  // CLOUD
  {
    id: "aws-vpc",
    name: "AWS VPC",
    type: "cloud",
    category: "cloud",
    vendor: "AWS",
    description: "Amazon Virtual Private Cloud",
    bandwidth: "100 Gbps",
    tags: ["cloud", "aws"],
    metadata: {
      Capabilities: "VPC, VPN, Direct Connect",
      Throughput: "Up to 100 Gbps",
    },
  },
  {
    id: "azure-vnet",
    name: "Azure VNet",
    type: "cloud",
    category: "cloud",
    vendor: "Microsoft",
    description: "Azure Virtual Network",
    bandwidth: "100 Gbps",
    tags: ["cloud", "azure"],
    metadata: {
      Capabilities: "VNet, VPN Gateway, ExpressRoute",
      Throughput: "Up to 100 Gbps",
    },
  },
  {
    id: "gcp-vpc",
    name: "GCP VPC",
    type: "cloud",
    category: "cloud",
    vendor: "Google",
    description: "Google Cloud Virtual Private Cloud",
    bandwidth: "100 Gbps",
    tags: ["cloud", "gcp"],
    metadata: {
      Capabilities: "VPC, Cloud VPN, Interconnect",
      Throughput: "Up to 100 Gbps",
    },
  },
  {
    id: "internet-wan",
    name: "Internet / WAN",
    type: "cloud",
    category: "cloud",
    vendor: "Generic",
    description: "External internet connection",
    bandwidth: "10 Gbps",
    tags: ["wan", "internet"],
    metadata: {
      Capabilities: "Internet connectivity",
      Throughput: "Provider dependent",
    },
  },
];

// Helper functions
export function getTemplatesByCategory(category: string): DeviceTemplate[] {
  return DEVICE_TEMPLATES.filter((template) => template.category === category);
}

export function getTemplatesByVendor(vendor: string): DeviceTemplate[] {
  return DEVICE_TEMPLATES.filter((template) => template.vendor === vendor);
}

export function getTemplatesByTag(tag: string): DeviceTemplate[] {
  return DEVICE_TEMPLATES.filter((template) => template.tags?.includes(tag));
}

export function searchTemplates(query: string): DeviceTemplate[] {
  const lowerQuery = query.toLowerCase();
  return DEVICE_TEMPLATES.filter(
    (template) =>
      template.name.toLowerCase().includes(lowerQuery) ||
      template.description.toLowerCase().includes(lowerQuery) ||
      template.vendor.toLowerCase().includes(lowerQuery) ||
      template.tags?.some((tag) => tag.toLowerCase().includes(lowerQuery))
  );
}

export function getVendors(): string[] {
  return Array.from(new Set(DEVICE_TEMPLATES.map((t) => t.vendor))).sort();
}

export function getTags(): string[] {
  const tags = new Set<string>();
  DEVICE_TEMPLATES.forEach((template) => {
    template.tags?.forEach((tag) => tags.add(tag));
  });
  return Array.from(tags).sort();
}

export function getTemplateCounts(): Record<string, number> {
  const counts: Record<string, number> = {};
  DEVICE_TEMPLATES.forEach((template) => {
    counts[template.category] = (counts[template.category] || 0) + 1;
  });
  return counts;
}
