import type { Node, Edge } from "reactflow";
import { MarkerType } from "reactflow";

export const PRESET_COLORS = [
  "#3b82f6", // Blue
  "#8b5cf6", // Purple
  "#ef4444", // Red
  "#f97316", // Orange
  "#eab308", // Yellow
  "#22c55e", // Green
  "#14b8a6", // Teal
  "#06b6d4", // Cyan
  "#ec4899", // Pink
  "#6366f1", // Indigo
  "#84cc16", // Lime
  "#f59e0b", // Amber
  "#10b981", // Emerald
  "#0ea5e9", // Sky
  "#a855f7", // Violet
  "#64748b", // Slate
  "#000000", // Black
  "#ffffff", // White
];

export const NETWORK_TEMPLATES: Record<
  "home" | "small" | "medium" | "enterprise",
  { nodes: Node[]; edges: Edge[] }
> = {
  home: {
    nodes: [
      {
        id: "modem-1",
        type: "custom",
        position: { x: 500, y: 50 },
        data: {
          label: "ISP Modem",
          type: "cloud",
          status: "online",
          ip: "192.168.0.1/24",
          bandwidth: "1 Gbps",
        },
      },
      {
        id: "router-1",
        type: "custom",
        position: { x: 500, y: 250 },
        data: {
          label: "Home Router",
          type: "router",
          status: "online",
          ip: "192.168.1.1/24",
          portCount: 4,
          powerConsumption: "18W",
          bandwidth: "1 Gbps",
          metadata: {
            Layer: "3",
            Capabilities: "Routing, NAT, WiFi",
          },
        },
      },
      {
        id: "ap-1",
        type: "custom",
        position: { x: 200, y: 450 },
        data: {
          label: "WiFi AP",
          type: "ap",
          status: "online",
          ip: "192.168.1.2/24",
          portCount: 1,
          powerConsumption: "12W",
          bandwidth: "1.5 Gbps",
          metadata: {
            Standard: "WiFi 6",
            Coverage: "93m²",
          },
        },
      },
      {
        id: "switch-1",
        type: "custom",
        position: { x: 800, y: 450 },
        data: {
          label: "Switch",
          type: "switch",
          status: "online",
          ip: "192.168.1.3/24",
          portCount: 8,
          powerConsumption: "10W",
          bandwidth: "1 Gbps",
          metadata: {
            Layer: "2",
          },
        },
      },
      {
        id: "pc-1",
        type: "custom",
        position: { x: 500, y: 650 },
        data: {
          label: "PC",
          type: "server",
          status: "online",
          ip: "192.168.1.10/24",
          portCount: 1,
          powerConsumption: "150W",
          bandwidth: "1 Gbps",
        },
      },
      {
        id: "nas-1",
        type: "custom",
        position: { x: 950, y: 650 },
        data: {
          label: "NAS",
          type: "nas",
          status: "online",
          ip: "192.168.1.20/24",
          portCount: 2,
          powerConsumption: "60W",
          bandwidth: "1 Gbps",
          metadata: {
            Storage: "Up to 48TB",
          },
        },
      },
    ],
    edges: [
      {
        id: "e1",
        source: "modem-1",
        target: "router-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e2",
        source: "router-1",
        target: "ap-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e3",
        source: "router-1",
        target: "switch-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e4",
        source: "switch-1",
        target: "pc-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e5",
        source: "switch-1",
        target: "nas-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
    ],
  },
  small: {
    nodes: [
      {
        id: "firewall-1",
        type: "custom",
        position: { x: 500, y: 50 },
        data: {
          label: "Firewall",
          type: "firewall",
          status: "online",
          ip: "10.0.0.1/24",
          portCount: 10,
          powerConsumption: "21W",
          bandwidth: "3 Gbps",
          metadata: {
            Layer: "3",
            Capabilities: "UTM, IPS, Antivirus",
            Throughput: "3 Gbps",
          },
        },
      },
      {
        id: "router-1",
        type: "custom",
        position: { x: 500, y: 250 },
        data: {
          label: "Core Router",
          type: "router",
          status: "online",
          ip: "10.0.1.1/24",
          portCount: 4,
          powerConsumption: "150W",
          bandwidth: "2 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            Capabilities: "Routing, NAT, VPN, QoS",
            Throughput: "2 Gbps",
            "Max VLANs": "4096",
          },
        },
      },
      {
        id: "switch-1",
        type: "custom",
        position: { x: 200, y: 450 },
        data: {
          label: "Office Switch",
          type: "switch",
          status: "online",
          ip: "10.0.1.10/24",
          vlan: "10",
          portCount: 24,
          powerConsumption: "190W",
          bandwidth: "1 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "2",
            "PoE Budget": "190W",
            "Max VLANs": "256",
          },
        },
      },
      {
        id: "ap-1",
        type: "custom",
        position: { x: 500, y: 450 },
        data: {
          label: "Office WiFi",
          type: "ap",
          status: "online",
          ip: "10.0.1.20/24",
          portCount: 1,
          powerConsumption: "16W",
          bandwidth: "5.3 Gbps",
          metadata: {
            Standard: "WiFi 6",
            Coverage: "140m²",
          },
        },
      },
      {
        id: "server-1",
        type: "custom",
        position: { x: 800, y: 450 },
        data: {
          label: "File Server",
          type: "server",
          status: "online",
          ip: "10.0.2.10/24",
          vlan: "20",
          portCount: 2,
          powerConsumption: "350W",
          bandwidth: "1 Gbps",
          metadata: {
            CPUs: "1x Intel Xeon",
            RAM: "Up to 256GB DDR4",
          },
        },
      },
      {
        id: "client-1",
        type: "custom",
        position: { x: 50, y: 650 },
        data: {
          label: "Workstation 1",
          type: "server",
          status: "online",
          ip: "10.0.1.100/24",
          portCount: 1,
          powerConsumption: "150W",
          bandwidth: "1 Gbps",
        },
      },
      {
        id: "client-2",
        type: "custom",
        position: { x: 350, y: 650 },
        data: {
          label: "Workstation 2",
          type: "server",
          status: "online",
          ip: "10.0.1.101/24",
          portCount: 1,
          powerConsumption: "150W",
          bandwidth: "1 Gbps",
        },
      },
    ],
    edges: [
      {
        id: "e1",
        source: "firewall-1",
        target: "router-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e2",
        source: "router-1",
        target: "switch-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps", vlan: "10" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e3",
        source: "router-1",
        target: "ap-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e4",
        source: "router-1",
        target: "server-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps", vlan: "20" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e5",
        source: "switch-1",
        target: "client-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e6",
        source: "switch-1",
        target: "client-2",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
    ],
  },
  medium: {
    nodes: [
      {
        id: "firewall-1",
        type: "custom",
        position: { x: 600, y: 50 },
        data: {
          label: "Edge Firewall",
          type: "firewall",
          status: "online",
          ip: "172.16.0.1/16",
          portCount: 18,
          powerConsumption: "60W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            Capabilities: "NGFW, Advanced Threats, SD-WAN",
            Throughput: "10 Gbps",
            "SFP+ Ports": "2",
          },
        },
      },
      {
        id: "router-1",
        type: "custom",
        position: { x: 600, y: 250 },
        data: {
          label: "Core Router",
          type: "router",
          status: "online",
          ip: "172.16.1.1/16",
          portCount: 4,
          powerConsumption: "250W",
          bandwidth: "5 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            Capabilities: "Routing, NAT, VPN, QoS, Advanced Security",
            Throughput: "5 Gbps",
            "Max VLANs": "4096",
            "SFP+ Ports": "2",
          },
        },
      },
      {
        id: "switch-core",
        type: "custom",
        position: { x: 600, y: 450 },
        data: {
          label: "Core Switch",
          type: "switch",
          status: "online",
          ip: "172.16.1.10/16",
          portCount: 52,
          powerConsumption: "250W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            "PoE Budget": "250W",
            "SFP+ Ports": "4",
            Throughput: "104 Gbps",
          },
        },
      },
      {
        id: "switch-office",
        type: "custom",
        position: { x: 150, y: 650 },
        data: {
          label: "Office Switch",
          type: "switch",
          status: "online",
          ip: "172.16.10.1/24",
          vlan: "10",
          portCount: 24,
          powerConsumption: "190W",
          bandwidth: "1 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "2",
            "PoE Budget": "190W",
          },
        },
      },
      {
        id: "switch-server",
        type: "custom",
        position: { x: 600, y: 650 },
        data: {
          label: "Server Switch",
          type: "switch",
          status: "online",
          ip: "172.16.20.1/24",
          vlan: "20",
          portCount: 28,
          powerConsumption: "495W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            "PoE Budget": "495W",
            "SFP+ Ports": "4",
            Throughput: "88 Gbps",
          },
        },
      },
      {
        id: "switch-iot",
        type: "custom",
        position: { x: 1050, y: 650 },
        data: {
          label: "IoT Switch",
          type: "switch",
          status: "online",
          ip: "172.16.30.1/24",
          vlan: "30",
          portCount: 24,
          powerConsumption: "190W",
          bandwidth: "1 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "2",
            "PoE Budget": "190W",
          },
        },
      },
      {
        id: "ap-1",
        type: "custom",
        position: { x: 50, y: 850 },
        data: {
          label: "Office WiFi",
          type: "ap",
          status: "online",
          ip: "172.16.10.20/24",
          portCount: 1,
          powerConsumption: "20W",
          bandwidth: "7.2 Gbps",
          metadata: {
            Standard: "WiFi 6",
            Coverage: "185m²",
          },
        },
      },
      {
        id: "client-1",
        type: "custom",
        position: { x: 250, y: 850 },
        data: {
          label: "Workstation",
          type: "server",
          status: "online",
          ip: "172.16.10.100/24",
          portCount: 1,
          powerConsumption: "150W",
          bandwidth: "1 Gbps",
        },
      },
      {
        id: "server-1",
        type: "custom",
        position: { x: 450, y: 850 },
        data: {
          label: "Web Server",
          type: "server",
          status: "online",
          ip: "172.16.20.10/24",
          portCount: 4,
          powerConsumption: "800W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            CPUs: "2x Intel Xeon Scalable",
            RAM: "Up to 3TB DDR4",
            "SFP+ Ports": "2",
          },
        },
      },
      {
        id: "server-2",
        type: "custom",
        position: { x: 650, y: 850 },
        data: {
          label: "Database",
          type: "server",
          status: "online",
          ip: "172.16.20.11/24",
          portCount: 4,
          powerConsumption: "800W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            CPUs: "2x Intel Xeon Scalable",
            RAM: "Up to 3TB DDR4",
            "SFP+ Ports": "2",
          },
        },
      },
      {
        id: "nas-1",
        type: "custom",
        position: { x: 850, y: 850 },
        data: {
          label: "NAS Storage",
          type: "nas",
          status: "online",
          ip: "172.16.20.20/24",
          portCount: 4,
          powerConsumption: "186W",
          bandwidth: "1 Gbps",
          rackUnits: 2,
          metadata: {
            Storage: "Up to 192TB",
            "Drive Bays": '12x 3.5"/2.5"',
          },
        },
      },
      {
        id: "camera-1",
        type: "custom",
        position: { x: 1150, y: 850 },
        data: {
          label: "Security Camera",
          type: "camera",
          status: "online",
          ip: "172.16.30.10/24",
          portCount: 1,
          powerConsumption: "12W",
          metadata: {
            Resolution: "4K (3840x2160)",
            Capabilities: "HDR, WDR, IR night vision",
          },
        },
      },
    ],
    edges: [
      {
        id: "e1",
        source: "firewall-1",
        target: "router-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10 Gbps",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e2",
        source: "router-1",
        target: "switch-core",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10 Gbps",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e3",
        source: "switch-core",
        target: "switch-office",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#22c55e" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps", vlan: "10" },
        label: "1 Gbps",
        style: { stroke: "#22c55e", strokeWidth: 2.5 },
      },
      {
        id: "e4",
        source: "switch-core",
        target: "switch-server",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "20" },
        label: "10 Gbps",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e5",
        source: "switch-core",
        target: "switch-iot",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#8b5cf6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps", vlan: "30" },
        label: "1 Gbps",
        style: { stroke: "#8b5cf6", strokeWidth: 2.5 },
      },
      {
        id: "e6",
        source: "switch-office",
        target: "ap-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e7",
        source: "switch-office",
        target: "client-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e8",
        source: "switch-server",
        target: "server-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10 Gbps",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e9",
        source: "switch-server",
        target: "server-2",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10 Gbps",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e10",
        source: "switch-server",
        target: "nas-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e11",
        source: "switch-iot",
        target: "camera-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
    ],
  },
  enterprise: {
    nodes: [
      // Internet Cloud
      {
        id: "cloud-1",
        type: "custom",
        position: { x: 1400, y: 50 },
        data: {
          label: "Internet/Cloud",
          type: "cloud",
          status: "online",
          bandwidth: "100 Gbps",
        },
      },
      // Edge Firewalls - Quadruple Redundancy
      {
        id: "firewall-edge-1",
        type: "custom",
        position: { x: 400, y: 250 },
        data: {
          label: "Edge FW 1 - Palo Alto PA-5220",
          type: "firewall",
          status: "online",
          ip: "10.0.0.1/8",
          portCount: 20,
          powerConsumption: "720W",
          bandwidth: "63 Gbps",
          rackUnits: 2,
          metadata: {
            Layer: "3",
            Capabilities: "NGFW, Advanced IPS, Threat Prevention, SSL Decrypt",
            "SFP+ Ports": "8",
            Throughput: "63 Gbps",
          },
        },
      },
      {
        id: "firewall-edge-2",
        type: "custom",
        position: { x: 900, y: 250 },
        data: {
          label: "Edge FW 2 - Palo Alto PA-5220",
          type: "firewall",
          status: "online",
          ip: "10.0.0.2/8",
          portCount: 20,
          powerConsumption: "720W",
          bandwidth: "63 Gbps",
          rackUnits: 2,
          metadata: {
            Layer: "3",
            Capabilities: "NGFW, Advanced IPS, Threat Prevention, SSL Decrypt",
            "SFP+ Ports": "8",
            Throughput: "63 Gbps",
          },
        },
      },
      {
        id: "firewall-edge-3",
        type: "custom",
        position: { x: 1600, y: 250 },
        data: {
          label: "Edge FW 3 - Fortinet FortiGate 600E",
          type: "firewall",
          status: "online",
          ip: "10.0.0.3/8",
          portCount: 16,
          powerConsumption: "120W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            Capabilities: "NGFW, Advanced IPS, Threat Prevention",
            "SFP+ Ports": "4",
            Throughput: "10 Gbps",
          },
        },
      },
      {
        id: "firewall-edge-4",
        type: "custom",
        position: { x: 2100, y: 250 },
        data: {
          label: "Edge FW 4 - Fortinet FortiGate 600E",
          type: "firewall",
          status: "online",
          ip: "10.0.0.4/8",
          portCount: 16,
          powerConsumption: "120W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            Capabilities: "NGFW, Advanced IPS, Threat Prevention",
            "SFP+ Ports": "4",
            Throughput: "10 Gbps",
          },
        },
      },
      // Core Routers - Quad Redundancy (Cisco ISR 4451)
      {
        id: "router-core-1",
        type: "custom",
        position: { x: 400, y: 500 },
        data: {
          label: "Core Router 1 - Cisco ISR 4451",
          type: "router",
          status: "online",
          ip: "10.0.1.1/8",
          portCount: 4,
          powerConsumption: "250W",
          bandwidth: "5 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            Capabilities: "Routing, NAT, VPN, QoS, Advanced Security",
            Throughput: "5 Gbps",
            "Max VLANs": "4096",
          },
        },
      },
      {
        id: "router-core-2",
        type: "custom",
        position: { x: 900, y: 500 },
        data: {
          label: "Core Router 2 - Cisco ISR 4451",
          type: "router",
          status: "online",
          ip: "10.0.1.2/8",
          portCount: 4,
          powerConsumption: "250W",
          bandwidth: "5 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            Capabilities: "Routing, NAT, VPN, QoS, Advanced Security",
            Throughput: "5 Gbps",
            "Max VLANs": "4096",
          },
        },
      },
      {
        id: "router-core-3",
        type: "custom",
        position: { x: 1600, y: 500 },
        data: {
          label: "Core Router 3 - MikroTik CCR2004",
          type: "router",
          status: "online",
          ip: "10.0.1.3/8",
          portCount: 18,
          powerConsumption: "55W",
          bandwidth: "16 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            Capabilities: "Routing, BGP, MPLS, VPLS, QoS",
            "SFP+ Ports": "2",
            Throughput: "16 Gbps",
            "Max VLANs": "4096",
          },
        },
      },
      {
        id: "router-core-4",
        type: "custom",
        position: { x: 2100, y: 500 },
        data: {
          label: "Core Router 4 - MikroTik CCR2004",
          type: "router",
          status: "online",
          ip: "10.0.1.4/8",
          portCount: 18,
          powerConsumption: "55W",
          bandwidth: "16 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            Capabilities: "Routing, BGP, MPLS, VPLS, QoS",
            "SFP+ Ports": "2",
            Throughput: "16 Gbps",
            "Max VLANs": "4096",
          },
        },
      },
      // Core Switches - Quad Redundancy (Cisco Catalyst 9300-48P)
      {
        id: "switch-core-1",
        type: "custom",
        position: { x: 400, y: 750 },
        data: {
          label: "Core SW 1 - Cisco 9300-48P",
          type: "switch",
          status: "online",
          ip: "10.0.2.1/8",
          portCount: 52,
          powerConsumption: "715W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            "PoE Budget": "715W",
            "SFP+ Ports": "4",
            Throughput: "440 Gbps",
            "Max VLANs": "4096",
          },
        },
      },
      {
        id: "switch-core-2",
        type: "custom",
        position: { x: 900, y: 750 },
        data: {
          label: "Core SW 2 - Cisco 9300-48P",
          type: "switch",
          status: "online",
          ip: "10.0.2.2/8",
          portCount: 52,
          powerConsumption: "715W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            "PoE Budget": "715W",
            "SFP+ Ports": "4",
            Throughput: "440 Gbps",
            "Max VLANs": "4096",
          },
        },
      },
      {
        id: "switch-core-3",
        type: "custom",
        position: { x: 1600, y: 750 },
        data: {
          label: "Core SW 3 - Aruba CX 6300",
          type: "switch",
          status: "online",
          ip: "10.0.2.3/8",
          portCount: 28,
          powerConsumption: "495W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            "PoE Budget": "495W",
            "SFP+ Ports": "4",
            Throughput: "208 Gbps",
            "Max VLANs": "4096",
          },
        },
      },
      {
        id: "switch-core-4",
        type: "custom",
        position: { x: 2100, y: 750 },
        data: {
          label: "Core SW 4 - Aruba CX 6300",
          type: "switch",
          status: "online",
          ip: "10.0.2.4/8",
          portCount: 28,
          powerConsumption: "495W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            "PoE Budget": "495W",
            "SFP+ Ports": "4",
            Throughput: "208 Gbps",
            "Max VLANs": "4096",
          },
        },
      },
      // DMZ Switches - Dual Redundancy (Cisco 2960X-24PS)
      {
        id: "switch-dmz-1",
        type: "custom",
        position: { x: 100, y: 1000 },
        data: {
          label: "DMZ SW 1 - Cisco 2960X-24PS",
          type: "switch",
          status: "online",
          ip: "10.1.0.1/16",
          vlan: "100",
          portCount: 28,
          powerConsumption: "370W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "2",
            "PoE Budget": "370W",
            "SFP+ Ports": "4",
            "Max VLANs": "4096",
          },
        },
      },
      {
        id: "switch-dmz-2",
        type: "custom",
        position: { x: 350, y: 1000 },
        data: {
          label: "DMZ SW 2 - Cisco 2960X-24PS",
          type: "switch",
          status: "online",
          ip: "10.1.0.2/16",
          vlan: "100",
          portCount: 28,
          powerConsumption: "370W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "2",
            "PoE Budget": "370W",
            "SFP+ Ports": "4",
            "Max VLANs": "4096",
          },
        },
      },
      // Server Switches - Quad Redundancy (Cisco 9300-48P)
      {
        id: "switch-server-1",
        type: "custom",
        position: { x: 700, y: 1000 },
        data: {
          label: "Server SW 1 - Cisco 9300-48P",
          type: "switch",
          status: "online",
          ip: "10.2.0.1/16",
          vlan: "200",
          portCount: 52,
          powerConsumption: "715W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            "PoE Budget": "715W",
            "SFP+ Ports": "4",
            Throughput: "440 Gbps",
            "Max VLANs": "4096",
          },
        },
      },
      {
        id: "switch-server-2",
        type: "custom",
        position: { x: 1000, y: 1000 },
        data: {
          label: "Server SW 2 - Cisco 9300-48P",
          type: "switch",
          status: "online",
          ip: "10.2.0.2/16",
          vlan: "200",
          portCount: 52,
          powerConsumption: "715W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            "PoE Budget": "715W",
            "SFP+ Ports": "4",
            Throughput: "440 Gbps",
            "Max VLANs": "4096",
          },
        },
      },
      {
        id: "switch-server-3",
        type: "custom",
        position: { x: 1300, y: 1000 },
        data: {
          label: "Server SW 3 - Meraki MS225-48FP",
          type: "switch",
          status: "online",
          ip: "10.2.0.3/16",
          vlan: "200",
          portCount: 52,
          powerConsumption: "740W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            "PoE Budget": "740W",
            "SFP+ Ports": "4",
            Throughput: "176 Gbps",
            "Max VLANs": "4096",
          },
        },
      },
      {
        id: "switch-server-4",
        type: "custom",
        position: { x: 1600, y: 1000 },
        data: {
          label: "Server SW 4 - Meraki MS225-48FP",
          type: "switch",
          status: "online",
          ip: "10.2.0.4/16",
          vlan: "200",
          portCount: 52,
          powerConsumption: "740W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            "PoE Budget": "740W",
            "SFP+ Ports": "4",
            Throughput: "176 Gbps",
            "Max VLANs": "4096",
          },
        },
      },
      // Office Switches - Triple Redundancy (UniFi & Cisco)
      {
        id: "switch-office-1",
        type: "custom",
        position: { x: 1950, y: 1000 },
        data: {
          label: "Office SW 1 - Cisco 2960X-48FPS",
          type: "switch",
          status: "online",
          ip: "10.3.0.1/16",
          vlan: "300",
          portCount: 52,
          powerConsumption: "740W",
          bandwidth: "1 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "2",
            "PoE Budget": "740W",
            "SFP+ Ports": "4",
            "Max VLANs": "4096",
          },
        },
      },
      {
        id: "switch-office-2",
        type: "custom",
        position: { x: 2400, y: 1000 },
        data: {
          label: "Office SW 2 - UniFi US-48-Pro",
          type: "switch",
          status: "online",
          ip: "10.3.0.2/16",
          vlan: "300",
          portCount: 52,
          powerConsumption: "250W",
          bandwidth: "1 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "2",
            "PoE Budget": "250W",
            "SFP+ Ports": "4",
            "Max VLANs": "128",
          },
        },
      },
      {
        id: "switch-office-3",
        type: "custom",
        position: { x: 2700, y: 1000 },
        data: {
          label: "Office SW 3 - UniFi US-48-Pro",
          type: "switch",
          status: "online",
          ip: "10.3.0.3/16",
          vlan: "300",
          portCount: 52,
          powerConsumption: "250W",
          bandwidth: "1 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "2",
            "PoE Budget": "250W",
            "SFP+ Ports": "4",
            "Max VLANs": "128",
          },
        },
      },
      // IoT/Security Switches - Dual Redundancy (UniFi)
      {
        id: "switch-iot-1",
        type: "custom",
        position: { x: 3150, y: 1000 },
        data: {
          label: "IoT SW 1 - UniFi US-24-PoE",
          type: "switch",
          status: "online",
          ip: "10.4.0.1/16",
          vlan: "400",
          portCount: 26,
          powerConsumption: "250W",
          bandwidth: "1 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "2",
            "PoE Budget": "250W",
            "SFP+ Ports": "2",
            "Max VLANs": "128",
          },
        },
      },
      {
        id: "switch-iot-2",
        type: "custom",
        position: { x: 3500, y: 1000 },
        data: {
          label: "IoT SW 2 - UniFi US-24-PoE",
          type: "switch",
          status: "online",
          ip: "10.4.0.2/16",
          vlan: "400",
          portCount: 26,
          powerConsumption: "250W",
          bandwidth: "1 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "2",
            "PoE Budget": "250W",
            "SFP+ Ports": "2",
            "Max VLANs": "128",
          },
        },
      },
      // DMZ Servers - Dual Redundancy (Dell PowerEdge R640)
      {
        id: "server-web-1",
        type: "custom",
        position: { x: 50, y: 1300 },
        data: {
          label: "Web Server 1 - Dell R640",
          type: "server",
          status: "online",
          ip: "10.1.0.10/16",
          vlan: "100",
          portCount: 4,
          powerConsumption: "800W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            CPUs: "2x Intel Xeon Scalable",
            RAM: "Up to 3TB DDR4",
            "SFP+ Ports": "2",
          },
        },
      },
      {
        id: "server-web-2",
        type: "custom",
        position: { x: 225, y: 1300 },
        data: {
          label: "Web Server 2 - Dell R640",
          type: "server",
          status: "online",
          ip: "10.1.0.11/16",
          vlan: "100",
          portCount: 4,
          powerConsumption: "800W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            CPUs: "2x Intel Xeon Scalable",
            RAM: "Up to 3TB DDR4",
            "SFP+ Ports": "2",
          },
        },
      },
      {
        id: "server-mail-1",
        type: "custom",
        position: { x: 400, y: 1300 },
        data: {
          label: "Mail Server 1 - Dell R640",
          type: "server",
          status: "online",
          ip: "10.1.0.20/16",
          vlan: "100",
          portCount: 4,
          powerConsumption: "800W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            CPUs: "2x Intel Xeon Scalable",
            RAM: "Up to 3TB DDR4",
            "SFP+ Ports": "2",
          },
        },
      },
      {
        id: "server-mail-2",
        type: "custom",
        position: { x: 575, y: 1300 },
        data: {
          label: "Mail Server 2 - Dell R640",
          type: "server",
          status: "online",
          ip: "10.1.0.21/16",
          vlan: "100",
          portCount: 4,
          powerConsumption: "800W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            CPUs: "2x Intel Xeon Scalable",
            RAM: "Up to 3TB DDR4",
            "SFP+ Ports": "2",
          },
        },
      },
      // Application Servers - Quad Redundancy (HPE ProLiant DL360)
      {
        id: "server-app-1",
        type: "custom",
        position: { x: 800, y: 1300 },
        data: {
          label: "App Server 1 - HPE DL360",
          type: "server",
          status: "online",
          ip: "10.2.0.10/16",
          vlan: "200",
          portCount: 4,
          powerConsumption: "1100W",
          bandwidth: "10 Gbps",
          rackUnits: 2,
          metadata: {
            CPUs: "2x Intel Xeon Scalable",
            RAM: "Up to 3TB DDR4",
            "SFP+ Ports": "2",
          },
        },
      },
      {
        id: "server-app-2",
        type: "custom",
        position: { x: 975, y: 1300 },
        data: {
          label: "App Server 2 - HPE DL360",
          type: "server",
          status: "online",
          ip: "10.2.0.11/16",
          vlan: "200",
          portCount: 4,
          powerConsumption: "1100W",
          bandwidth: "10 Gbps",
          rackUnits: 2,
          metadata: {
            CPUs: "2x Intel Xeon Scalable",
            RAM: "Up to 3TB DDR4",
            "SFP+ Ports": "2",
          },
        },
      },
      {
        id: "server-app-3",
        type: "custom",
        position: { x: 1150, y: 1300 },
        data: {
          label: "App Server 3 - HPE DL360",
          type: "server",
          status: "online",
          ip: "10.2.0.12/16",
          vlan: "200",
          portCount: 4,
          powerConsumption: "1100W",
          bandwidth: "10 Gbps",
          rackUnits: 2,
          metadata: {
            CPUs: "2x Intel Xeon Scalable",
            RAM: "Up to 3TB DDR4",
            "SFP+ Ports": "2",
          },
        },
      },
      {
        id: "server-app-4",
        type: "custom",
        position: { x: 1325, y: 1300 },
        data: {
          label: "App Server 4 - HPE DL360",
          type: "server",
          status: "online",
          ip: "10.2.0.13/16",
          vlan: "200",
          portCount: 4,
          powerConsumption: "1100W",
          bandwidth: "10 Gbps",
          rackUnits: 2,
          metadata: {
            CPUs: "2x Intel Xeon Scalable",
            RAM: "Up to 3TB DDR4",
            "SFP+ Ports": "2",
          },
        },
      },
      // Database Cluster - Triple Redundancy (Dell PowerEdge R740)
      {
        id: "server-db-1",
        type: "custom",
        position: { x: 1550, y: 1300 },
        data: {
          label: "DB Primary - Dell R740",
          type: "server",
          status: "online",
          ip: "10.2.0.20/16",
          vlan: "200",
          portCount: 4,
          powerConsumption: "1100W",
          bandwidth: "10 Gbps",
          rackUnits: 2,
          metadata: {
            CPUs: "2x Intel Xeon Scalable",
            RAM: "Up to 3TB DDR4",
            "SFP+ Ports": "2",
          },
        },
      },
      {
        id: "server-db-2",
        type: "custom",
        position: { x: 1725, y: 1300 },
        data: {
          label: "DB Secondary - Dell R740",
          type: "server",
          status: "online",
          ip: "10.2.0.21/16",
          vlan: "200",
          portCount: 4,
          powerConsumption: "1100W",
          bandwidth: "10 Gbps",
          rackUnits: 2,
          metadata: {
            CPUs: "2x Intel Xeon Scalable",
            RAM: "Up to 3TB DDR4",
            "SFP+ Ports": "2",
          },
        },
      },
      {
        id: "server-db-3",
        type: "custom",
        position: { x: 1900, y: 1300 },
        data: {
          label: "DB Tertiary - Dell R740",
          type: "server",
          status: "online",
          ip: "10.2.0.22/16",
          vlan: "200",
          portCount: 4,
          powerConsumption: "1100W",
          bandwidth: "10 Gbps",
          rackUnits: 2,
          metadata: {
            CPUs: "2x Intel Xeon Scalable",
            RAM: "Up to 3TB DDR4",
            "SFP+ Ports": "2",
          },
        },
      },
      // Storage Arrays - Dual Redundancy (Synology RS4021xs+)
      {
        id: "nas-1",
        type: "custom",
        position: { x: 2125, y: 1300 },
        data: {
          label: "Storage 1 - Synology RS4021xs+",
          type: "nas",
          status: "online",
          ip: "10.2.0.30/16",
          vlan: "200",
          portCount: 4,
          powerConsumption: "314W",
          bandwidth: "10 Gbps",
          rackUnits: 3,
          metadata: {
            Storage: "Up to 256TB",
            "Drive Bays": '16x 3.5"/2.5"',
            NICs: "4x 1GbE, 2x 10GbE",
            "SFP+ Ports": "2",
          },
        },
      },
      {
        id: "nas-2",
        type: "custom",
        position: { x: 2300, y: 1300 },
        data: {
          label: "Storage 2 - Synology RS4021xs+",
          type: "nas",
          status: "online",
          ip: "10.2.0.31/16",
          vlan: "200",
          portCount: 4,
          powerConsumption: "314W",
          bandwidth: "10 Gbps",
          rackUnits: 3,
          metadata: {
            Storage: "Up to 256TB",
            "Drive Bays": '16x 3.5"/2.5"',
            NICs: "4x 1GbE, 2x 10GbE",
            "SFP+ Ports": "2",
          },
        },
      },
      // Backup NAS (QNAP TVS-h1688X)
      {
        id: "nas-backup",
        type: "custom",
        position: { x: 2475, y: 1300 },
        data: {
          label: "Backup NAS - QNAP TVS-h1688X",
          type: "nas",
          status: "online",
          ip: "10.2.0.40/16",
          vlan: "200",
          portCount: 4,
          powerConsumption: "186W",
          bandwidth: "10 Gbps",
          rackUnits: 2,
          metadata: {
            Storage: "Up to 192TB",
            "Drive Bays": '12x 3.5"/2.5"',
            NICs: "2x 10GbE",
          },
        },
      },
      // WiFi Access Points - Multiple (UniFi WiFi 6)
      {
        id: "ap-1",
        type: "custom",
        position: { x: 2700, y: 1300 },
        data: {
          label: "Office WiFi 1 - UniFi U6 Enterprise",
          type: "ap",
          status: "online",
          ip: "10.3.0.10/16",
          vlan: "300",
          portCount: 1,
          powerConsumption: "20W",
          bandwidth: "7.2 Gbps",
          metadata: {
            Standard: "WiFi 6",
            Coverage: "185m²",
            Capabilities: "Tri-band, 160MHz, 4x4 MU-MIMO",
          },
        },
      },
      {
        id: "ap-2",
        type: "custom",
        position: { x: 2875, y: 1300 },
        data: {
          label: "Office WiFi 2 - UniFi U6 Enterprise",
          type: "ap",
          status: "online",
          ip: "10.3.0.11/16",
          vlan: "300",
          portCount: 1,
          powerConsumption: "20W",
          bandwidth: "7.2 Gbps",
          metadata: {
            Standard: "WiFi 6",
            Coverage: "185m²",
            Capabilities: "Tri-band, 160MHz, 4x4 MU-MIMO",
          },
        },
      },
      {
        id: "ap-3",
        type: "custom",
        position: { x: 3050, y: 1300 },
        data: {
          label: "Office WiFi 3 - Cisco Meraki MR56",
          type: "ap",
          status: "online",
          ip: "10.3.0.12/16",
          vlan: "300",
          portCount: 1,
          powerConsumption: "12W",
          bandwidth: "3 Gbps",
          metadata: {
            Standard: "WiFi 6",
            Coverage: "93m²",
            Capabilities: "Dual-band, 2x2 MU-MIMO",
          },
        },
      },
      {
        id: "ap-4",
        type: "custom",
        position: { x: 3225, y: 1300 },
        data: {
          label: "Office WiFi 4 - Cisco Meraki MR56",
          type: "ap",
          status: "online",
          ip: "10.3.0.13/16",
          vlan: "300",
          portCount: 1,
          powerConsumption: "12W",
          bandwidth: "3 Gbps",
          metadata: {
            Standard: "WiFi 6",
            Coverage: "93m²",
            Capabilities: "Dual-band, 2x2 MU-MIMO",
          },
        },
      },
      // Security Cameras - Multiple (Axis Communications)
      {
        id: "camera-1",
        type: "custom",
        position: { x: 3450, y: 1300 },
        data: {
          label: "Camera 1 - Axis Q6135-LE",
          type: "camera",
          status: "online",
          ip: "10.4.0.10/16",
          vlan: "400",
          portCount: 1,
          powerConsumption: "12W",
          metadata: {
            Resolution: "4K (3840x2160)",
            Capabilities: "HDR, WDR, IR night vision",
          },
        },
      },
      {
        id: "camera-2",
        type: "custom",
        position: { x: 3625, y: 1300 },
        data: {
          label: "Camera 2 - Axis Q6135-LE",
          type: "camera",
          status: "online",
          ip: "10.4.0.11/16",
          vlan: "400",
          portCount: 1,
          powerConsumption: "12W",
          metadata: {
            Resolution: "4K (3840x2160)",
            Capabilities: "HDR, WDR, IR night vision",
          },
        },
      },
      {
        id: "camera-3",
        type: "custom",
        position: { x: 3800, y: 1300 },
        data: {
          label: "Camera 3 - Axis Q6135-LE",
          type: "camera",
          status: "online",
          ip: "10.4.0.12/16",
          vlan: "400",
          portCount: 1,
          powerConsumption: "12W",
          metadata: {
            Resolution: "4K (3840x2160)",
            Capabilities: "HDR, WDR, IR night vision",
          },
        },
      },
      {
        id: "camera-4",
        type: "custom",
        position: { x: 3975, y: 1300 },
        data: {
          label: "Camera 4 - Axis Q6135-LE",
          type: "camera",
          status: "online",
          ip: "10.4.0.13/16",
          vlan: "400",
          portCount: 1,
          powerConsumption: "12W",
          metadata: {
            Resolution: "4K (3840x2160)",
            Capabilities: "HDR, WDR, IR night vision",
          },
        },
      },
      // Load Balancer (F5 BIG-IP)
      {
        id: "loadbalancer-1",
        type: "custom",
        position: { x: 50, y: 750 },
        data: {
          label: "Load Balancer - F5 BIG-IP",
          type: "server",
          status: "online",
          ip: "10.0.5.1/8",
          portCount: 8,
          powerConsumption: "350W",
          bandwidth: "10 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "7",
            Capabilities: "Load Balancing, SSL Offload, WAF",
            Throughput: "10 Gbps",
          },
        },
      },
      // VPN Concentrator (Cisco ASA 5516-X)
      {
        id: "vpn-1",
        type: "custom",
        position: { x: 3500, y: 750 },
        data: {
          label: "VPN Gateway - Cisco ASA 5516-X",
          type: "firewall",
          status: "online",
          ip: "10.0.6.1/8",
          portCount: 8,
          powerConsumption: "70W",
          bandwidth: "1.2 Gbps",
          rackUnits: 1,
          metadata: {
            Layer: "3",
            Capabilities: "IPsec VPN, SSL VPN, Firewall",
            "VPN Throughput": "1.2 Gbps",
            "Max VPN Peers": "750",
          },
        },
      },
    ],
    edges: [
      // Cloud to ALL Edge Firewalls (Quad Redundancy)
      {
        id: "e1",
        source: "cloud-1",
        target: "firewall-edge-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "100 Gbps" },
        label: "100G",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e2",
        source: "cloud-1",
        target: "firewall-edge-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "100 Gbps" },
        label: "100G",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e3",
        source: "cloud-1",
        target: "firewall-edge-3",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "100 Gbps" },
        label: "100G",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e4",
        source: "cloud-1",
        target: "firewall-edge-4",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "100 Gbps" },
        label: "100G",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },

      // Edge Firewalls to Core Routers (Each router connects to one firewall to stay within port limits)
      {
        id: "e5",
        source: "firewall-edge-1",
        target: "router-core-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#f59e0b" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#f59e0b", strokeWidth: 3.5 },
      },
      {
        id: "e8",
        source: "firewall-edge-2",
        target: "router-core-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#f59e0b" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#f59e0b", strokeWidth: 3.5 },
      },
      {
        id: "e9",
        source: "firewall-edge-3",
        target: "router-core-3",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#f59e0b" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#f59e0b", strokeWidth: 3.5 },
      },
      {
        id: "e12",
        source: "firewall-edge-4",
        target: "router-core-4",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#f59e0b" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#f59e0b", strokeWidth: 3.5 },
      },

      // Core Routers to Core Switches (Each router to each switch)
      {
        id: "e13",
        source: "router-core-1",
        target: "switch-core-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#22c55e" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#22c55e", strokeWidth: 3.5 },
      },
      {
        id: "e14",
        source: "router-core-1",
        target: "switch-core-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#22c55e" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#22c55e", strokeWidth: 3.5 },
      },
      {
        id: "e15",
        source: "router-core-2",
        target: "switch-core-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#22c55e" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#22c55e", strokeWidth: 3.5 },
      },
      {
        id: "e16",
        source: "router-core-2",
        target: "switch-core-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#22c55e" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#22c55e", strokeWidth: 3.5 },
      },
      {
        id: "e17",
        source: "router-core-3",
        target: "switch-core-3",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#22c55e" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#22c55e", strokeWidth: 3.5 },
      },
      {
        id: "e18",
        source: "router-core-3",
        target: "switch-core-4",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#22c55e" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#22c55e", strokeWidth: 3.5 },
      },
      {
        id: "e19",
        source: "router-core-4",
        target: "switch-core-3",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#22c55e" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#22c55e", strokeWidth: 3.5 },
      },
      {
        id: "e20",
        source: "router-core-4",
        target: "switch-core-4",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#22c55e" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#22c55e", strokeWidth: 3.5 },
      },

      // Core Switch Full Mesh Interconnect
      {
        id: "e21",
        source: "switch-core-1",
        target: "switch-core-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#14b8a6" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#14b8a6", strokeWidth: 3.5 },
      },
      {
        id: "e22",
        source: "switch-core-1",
        target: "switch-core-3",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#14b8a6" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#14b8a6", strokeWidth: 3.5 },
      },
      {
        id: "e23",
        source: "switch-core-1",
        target: "switch-core-4",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#14b8a6" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#14b8a6", strokeWidth: 3.5 },
      },
      {
        id: "e24",
        source: "switch-core-2",
        target: "switch-core-3",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#14b8a6" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#14b8a6", strokeWidth: 3.5 },
      },
      {
        id: "e25",
        source: "switch-core-2",
        target: "switch-core-4",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#14b8a6" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#14b8a6", strokeWidth: 3.5 },
      },
      {
        id: "e26",
        source: "switch-core-3",
        target: "switch-core-4",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#14b8a6" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#14b8a6", strokeWidth: 3.5 },
      },

      // Core Switches to DMZ Switches (Dual Uplinks from both DMZ switches)
      {
        id: "e27",
        source: "switch-core-1",
        target: "switch-dmz-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#f97316" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "100" },
        label: "10G",
        style: { stroke: "#f97316", strokeWidth: 2.5 },
      },
      {
        id: "e28",
        source: "switch-core-2",
        target: "switch-dmz-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#f97316" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "100" },
        label: "10G",
        style: { stroke: "#f97316", strokeWidth: 2.5 },
      },
      {
        id: "e29",
        source: "switch-core-1",
        target: "switch-dmz-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#f97316" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "100" },
        label: "10G",
        style: { stroke: "#f97316", strokeWidth: 2.5 },
      },
      {
        id: "e30",
        source: "switch-core-2",
        target: "switch-dmz-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#f97316" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "100" },
        label: "10G",
        style: { stroke: "#f97316", strokeWidth: 2.5 },
      },

      // Core Switches to Server Switches (Each core to each server switch)
      {
        id: "e31",
        source: "switch-core-1",
        target: "switch-server-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#8b5cf6" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps", vlan: "200" },
        label: "40G",
        style: { stroke: "#8b5cf6", strokeWidth: 3.5 },
      },
      {
        id: "e32",
        source: "switch-core-1",
        target: "switch-server-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#8b5cf6" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps", vlan: "200" },
        label: "40G",
        style: { stroke: "#8b5cf6", strokeWidth: 3.5 },
      },
      {
        id: "e33",
        source: "switch-core-2",
        target: "switch-server-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#8b5cf6" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps", vlan: "200" },
        label: "40G",
        style: { stroke: "#8b5cf6", strokeWidth: 3.5 },
      },
      {
        id: "e34",
        source: "switch-core-2",
        target: "switch-server-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#8b5cf6" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps", vlan: "200" },
        label: "40G",
        style: { stroke: "#8b5cf6", strokeWidth: 3.5 },
      },
      {
        id: "e35",
        source: "switch-core-3",
        target: "switch-server-3",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#8b5cf6" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps", vlan: "200" },
        label: "40G",
        style: { stroke: "#8b5cf6", strokeWidth: 3.5 },
      },
      {
        id: "e36",
        source: "switch-core-3",
        target: "switch-server-4",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#8b5cf6" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps", vlan: "200" },
        label: "40G",
        style: { stroke: "#8b5cf6", strokeWidth: 3.5 },
      },
      {
        id: "e37",
        source: "switch-core-4",
        target: "switch-server-3",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#8b5cf6" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps", vlan: "200" },
        label: "40G",
        style: { stroke: "#8b5cf6", strokeWidth: 3.5 },
      },
      {
        id: "e38",
        source: "switch-core-4",
        target: "switch-server-4",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#8b5cf6" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps", vlan: "200" },
        label: "40G",
        style: { stroke: "#8b5cf6", strokeWidth: 3.5 },
      },

      // Core Switches to Office Switches
      {
        id: "e39",
        source: "switch-core-1",
        target: "switch-office-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "300" },
        label: "10G",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e40",
        source: "switch-core-2",
        target: "switch-office-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "300" },
        label: "10G",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e41",
        source: "switch-core-2",
        target: "switch-office-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "300" },
        label: "10G",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e42",
        source: "switch-core-3",
        target: "switch-office-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "300" },
        label: "10G",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e43",
        source: "switch-core-3",
        target: "switch-office-3",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "300" },
        label: "10G",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e44",
        source: "switch-core-4",
        target: "switch-office-3",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "300" },
        label: "10G",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },

      // Core Switches to IoT Switches
      {
        id: "e45",
        source: "switch-core-3",
        target: "switch-iot-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ec4899" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "400" },
        label: "10G",
        style: { stroke: "#ec4899", strokeWidth: 2.5 },
      },
      {
        id: "e46",
        source: "switch-core-4",
        target: "switch-iot-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ec4899" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "400" },
        label: "10G",
        style: { stroke: "#ec4899", strokeWidth: 2.5 },
      },
      {
        id: "e47",
        source: "switch-core-3",
        target: "switch-iot-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ec4899" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "400" },
        label: "10G",
        style: { stroke: "#ec4899", strokeWidth: 2.5 },
      },
      {
        id: "e48",
        source: "switch-core-4",
        target: "switch-iot-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ec4899" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "400" },
        label: "10G",
        style: { stroke: "#ec4899", strokeWidth: 2.5 },
      },

      // DMZ Switches to Servers (Dual connections)
      {
        id: "e49",
        source: "switch-dmz-1",
        target: "server-web-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#ef4444", strokeWidth: 3 },
      },
      {
        id: "e50",
        source: "switch-dmz-2",
        target: "server-web-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#ef4444", strokeWidth: 3 },
      },
      {
        id: "e51",
        source: "switch-dmz-1",
        target: "server-web-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#ef4444", strokeWidth: 3 },
      },
      {
        id: "e52",
        source: "switch-dmz-2",
        target: "server-web-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#ef4444", strokeWidth: 3 },
      },
      {
        id: "e53",
        source: "switch-dmz-1",
        target: "server-mail-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#ef4444", strokeWidth: 3 },
      },
      {
        id: "e54",
        source: "switch-dmz-2",
        target: "server-mail-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#ef4444", strokeWidth: 3 },
      },
      {
        id: "e55",
        source: "switch-dmz-1",
        target: "server-mail-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#ef4444", strokeWidth: 3 },
      },
      {
        id: "e56",
        source: "switch-dmz-2",
        target: "server-mail-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#ef4444", strokeWidth: 3 },
      },

      // Server Switches to App Servers (Each app server dual-homed)
      {
        id: "e57",
        source: "switch-server-1",
        target: "server-app-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#10b981" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#10b981", strokeWidth: 3 },
      },
      {
        id: "e58",
        source: "switch-server-2",
        target: "server-app-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#10b981" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#10b981", strokeWidth: 3 },
      },
      {
        id: "e59",
        source: "switch-server-1",
        target: "server-app-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#10b981" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#10b981", strokeWidth: 3 },
      },
      {
        id: "e60",
        source: "switch-server-2",
        target: "server-app-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#10b981" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#10b981", strokeWidth: 3 },
      },
      {
        id: "e61",
        source: "switch-server-3",
        target: "server-app-3",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#10b981" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#10b981", strokeWidth: 3 },
      },
      {
        id: "e62",
        source: "switch-server-4",
        target: "server-app-3",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#10b981" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#10b981", strokeWidth: 3 },
      },
      {
        id: "e63",
        source: "switch-server-3",
        target: "server-app-4",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#10b981" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#10b981", strokeWidth: 3 },
      },
      {
        id: "e64",
        source: "switch-server-4",
        target: "server-app-4",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#10b981" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#10b981", strokeWidth: 3 },
      },

      // Server Switches to Database Cluster (High bandwidth, each DB server quad-homed)
      {
        id: "e65",
        source: "switch-server-1",
        target: "server-db-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e66",
        source: "switch-server-2",
        target: "server-db-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e67",
        source: "switch-server-1",
        target: "server-db-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e68",
        source: "switch-server-2",
        target: "server-db-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e69",
        source: "switch-server-3",
        target: "server-db-3",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e70",
        source: "switch-server-4",
        target: "server-db-3",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },

      // Server Switches to Storage Arrays (Each NAS quad-homed for max throughput)
      {
        id: "e71",
        source: "switch-server-1",
        target: "nas-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#eab308" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#eab308", strokeWidth: 3.5 },
      },
      {
        id: "e72",
        source: "switch-server-2",
        target: "nas-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#eab308" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#eab308", strokeWidth: 3.5 },
      },
      {
        id: "e73",
        source: "switch-server-3",
        target: "nas-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#eab308" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#eab308", strokeWidth: 3.5 },
      },
      {
        id: "e74",
        source: "switch-server-4",
        target: "nas-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#eab308" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40G",
        style: { stroke: "#eab308", strokeWidth: 3.5 },
      },
      {
        id: "e75",
        source: "switch-server-2",
        target: "nas-backup",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#eab308" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#eab308", strokeWidth: 2.5 },
      },
      {
        id: "e76",
        source: "switch-server-3",
        target: "nas-backup",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#eab308" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#eab308", strokeWidth: 2.5 },
      },

      // Office Switches to WiFi APs (Single connection per AP due to port constraints)
      {
        id: "e77",
        source: "switch-office-1",
        target: "ap-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#06b6d4" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1G PoE",
        style: { stroke: "#06b6d4", strokeWidth: 2 },
      },
      {
        id: "e79",
        source: "switch-office-1",
        target: "ap-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#06b6d4" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1G PoE",
        style: { stroke: "#06b6d4", strokeWidth: 2 },
      },
      {
        id: "e82",
        source: "switch-office-3",
        target: "ap-3",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#06b6d4" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1G PoE",
        style: { stroke: "#06b6d4", strokeWidth: 2 },
      },
      {
        id: "e84",
        source: "switch-office-3",
        target: "ap-4",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#06b6d4" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1G PoE",
        style: { stroke: "#06b6d4", strokeWidth: 2 },
      },

      // IoT Switches to Security Cameras (Single connection per camera due to port constraints)
      {
        id: "e85",
        source: "switch-iot-1",
        target: "camera-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#a855f7" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1G PoE",
        style: { stroke: "#a855f7", strokeWidth: 2 },
      },
      {
        id: "e87",
        source: "switch-iot-1",
        target: "camera-2",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#a855f7" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1G PoE",
        style: { stroke: "#a855f7", strokeWidth: 2 },
      },
      {
        id: "e89",
        source: "switch-iot-1",
        target: "camera-3",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#a855f7" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1G PoE",
        style: { stroke: "#a855f7", strokeWidth: 2 },
      },
      {
        id: "e91",
        source: "switch-iot-1",
        target: "camera-4",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#a855f7" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1G PoE",
        style: { stroke: "#a855f7", strokeWidth: 2 },
      },

      // Load Balancer to Core (Dual-homed to core switches)
      {
        id: "e93",
        source: "switch-core-1",
        target: "loadbalancer-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#84cc16" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#84cc16", strokeWidth: 2.5 },
      },
      {
        id: "e94",
        source: "switch-core-2",
        target: "loadbalancer-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#84cc16" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#84cc16", strokeWidth: 2.5 },
      },

      // VPN Gateway to Core (Dual-homed)
      {
        id: "e95",
        source: "switch-core-3",
        target: "vpn-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#f59e0b" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#f59e0b", strokeWidth: 2.5 },
      },
      {
        id: "e96",
        source: "switch-core-4",
        target: "vpn-1",
        type: "smoothstep",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#f59e0b" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps" },
        label: "10G",
        style: { stroke: "#f59e0b", strokeWidth: 2.5 },
      },
    ],
  },
};
