import type { Node, Edge } from "reactflow";
import { MarkerType } from "reactflow";

export const PRESET_COLORS = [
  "#3b82f6", // Blue
  "#8b5cf6", // Purple
  "#ef4444", // Red
  "#f97316", // Orange
  "#eab308", // Yellow
  "#22c55e", // Green
  "#14b8a6", // Teal
  "#06b6d4", // Cyan
  "#ec4899", // Pink
  "#6366f1", // Indigo
  "#84cc16", // Lime
  "#f59e0b", // Amber
  "#10b981", // Emerald
  "#0ea5e9", // Sky
  "#a855f7", // Violet
  "#64748b", // Slate
  "#000000", // Black
  "#ffffff", // White
];

export const NETWORK_TEMPLATES: Record<
  "home" | "small" | "medium" | "enterprise",
  { nodes: Node[]; edges: Edge[] }
> = {
  home: {
    nodes: [
      {
        id: "modem-1",
        type: "custom",
        position: { x: 500, y: 50 },
        data: {
          label: "ISP Modem",
          type: "cloud",
          status: "online",
          ipAddress: "192.168.0.1",
        },
      },
      {
        id: "router-1",
        type: "custom",
        position: { x: 500, y: 250 },
        data: {
          label: "Home Router",
          type: "router",
          status: "online",
          ipAddress: "192.168.1.1",
        },
      },
      {
        id: "ap-1",
        type: "custom",
        position: { x: 200, y: 450 },
        data: {
          label: "WiFi AP",
          type: "ap",
          status: "online",
          ipAddress: "192.168.1.2",
        },
      },
      {
        id: "switch-1",
        type: "custom",
        position: { x: 800, y: 450 },
        data: {
          label: "Switch",
          type: "switch",
          status: "online",
          ipAddress: "192.168.1.3",
        },
      },
      {
        id: "pc-1",
        type: "custom",
        position: { x: 500, y: 650 },
        data: {
          label: "PC",
          type: "server",
          status: "online",
          ipAddress: "192.168.1.10",
        },
      },
      {
        id: "nas-1",
        type: "custom",
        position: { x: 950, y: 650 },
        data: {
          label: "NAS",
          type: "nas",
          status: "online",
          ipAddress: "192.168.1.20",
        },
      },
    ],
    edges: [
      {
        id: "e1",
        source: "modem-1",
        target: "router-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e2",
        source: "router-1",
        target: "ap-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e3",
        source: "router-1",
        target: "switch-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e4",
        source: "switch-1",
        target: "pc-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e5",
        source: "switch-1",
        target: "nas-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
    ],
  },
  small: {
    nodes: [
      {
        id: "firewall-1",
        type: "custom",
        position: { x: 500, y: 50 },
        data: {
          label: "Firewall",
          type: "firewall",
          status: "online",
          ipAddress: "10.0.0.1",
        },
      },
      {
        id: "router-1",
        type: "custom",
        position: { x: 500, y: 250 },
        data: {
          label: "Core Router",
          type: "router",
          status: "online",
          ipAddress: "10.0.1.1",
        },
      },
      {
        id: "switch-1",
        type: "custom",
        position: { x: 200, y: 450 },
        data: {
          label: "Office Switch",
          type: "switch",
          status: "online",
          ipAddress: "10.0.1.10",
          vlan: "10",
        },
      },
      {
        id: "ap-1",
        type: "custom",
        position: { x: 500, y: 450 },
        data: {
          label: "Office WiFi",
          type: "ap",
          status: "online",
          ipAddress: "10.0.1.20",
        },
      },
      {
        id: "server-1",
        type: "custom",
        position: { x: 800, y: 450 },
        data: {
          label: "File Server",
          type: "server",
          status: "online",
          ipAddress: "10.0.2.10",
          vlan: "20",
        },
      },
      {
        id: "client-1",
        type: "custom",
        position: { x: 50, y: 650 },
        data: {
          label: "Workstation 1",
          type: "server",
          status: "online",
          ipAddress: "10.0.1.100",
        },
      },
      {
        id: "client-2",
        type: "custom",
        position: { x: 350, y: 650 },
        data: {
          label: "Workstation 2",
          type: "server",
          status: "online",
          ipAddress: "10.0.1.101",
        },
      },
    ],
    edges: [
      {
        id: "e1",
        source: "firewall-1",
        target: "router-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e2",
        source: "router-1",
        target: "switch-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps", vlan: "10" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e3",
        source: "router-1",
        target: "ap-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e4",
        source: "router-1",
        target: "server-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps", vlan: "20" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e5",
        source: "switch-1",
        target: "client-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e6",
        source: "switch-1",
        target: "client-2",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
    ],
  },
  medium: {
    nodes: [
      {
        id: "firewall-1",
        type: "custom",
        position: { x: 600, y: 50 },
        data: {
          label: "Edge Firewall",
          type: "firewall",
          status: "online",
          ipAddress: "172.16.0.1",
        },
      },
      {
        id: "router-1",
        type: "custom",
        position: { x: 600, y: 250 },
        data: {
          label: "Core Router",
          type: "router",
          status: "online",
          ipAddress: "172.16.1.1",
        },
      },
      {
        id: "switch-core",
        type: "custom",
        position: { x: 600, y: 450 },
        data: {
          label: "Core Switch",
          type: "switch",
          status: "online",
          ipAddress: "172.16.1.10",
        },
      },
      {
        id: "switch-office",
        type: "custom",
        position: { x: 150, y: 650 },
        data: {
          label: "Office Switch",
          type: "switch",
          status: "online",
          ipAddress: "172.16.10.1",
          vlan: "10",
        },
      },
      {
        id: "switch-server",
        type: "custom",
        position: { x: 600, y: 650 },
        data: {
          label: "Server Switch",
          type: "switch",
          status: "online",
          ipAddress: "172.16.20.1",
          vlan: "20",
        },
      },
      {
        id: "switch-iot",
        type: "custom",
        position: { x: 1050, y: 650 },
        data: {
          label: "IoT Switch",
          type: "switch",
          status: "online",
          ipAddress: "172.16.30.1",
          vlan: "30",
        },
      },
      {
        id: "ap-1",
        type: "custom",
        position: { x: 50, y: 850 },
        data: {
          label: "Office WiFi",
          type: "ap",
          status: "online",
          ipAddress: "172.16.10.20",
        },
      },
      {
        id: "client-1",
        type: "custom",
        position: { x: 250, y: 850 },
        data: {
          label: "Workstation",
          type: "server",
          status: "online",
          ipAddress: "172.16.10.100",
        },
      },
      {
        id: "server-1",
        type: "custom",
        position: { x: 450, y: 850 },
        data: {
          label: "Web Server",
          type: "server",
          status: "online",
          ipAddress: "172.16.20.10",
        },
      },
      {
        id: "server-2",
        type: "custom",
        position: { x: 650, y: 850 },
        data: {
          label: "Database",
          type: "server",
          status: "online",
          ipAddress: "172.16.20.11",
        },
      },
      {
        id: "nas-1",
        type: "custom",
        position: { x: 850, y: 850 },
        data: {
          label: "NAS Storage",
          type: "nas",
          status: "online",
          ipAddress: "172.16.20.20",
        },
      },
      {
        id: "camera-1",
        type: "custom",
        position: { x: 1150, y: 850 },
        data: {
          label: "Security Camera",
          type: "camera",
          status: "online",
          ipAddress: "172.16.30.10",
        },
      },
    ],
    edges: [
      {
        id: "e1",
        source: "firewall-1",
        target: "router-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "10 Gbps" },
        label: "10 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e2",
        source: "router-1",
        target: "switch-core",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "10 Gbps" },
        label: "10 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e3",
        source: "switch-core",
        target: "switch-office",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#22c55e" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps", vlan: "10" },
        label: "1 Gbps",
        style: { stroke: "#22c55e", strokeWidth: 2.5 },
      },
      {
        id: "e4",
        source: "switch-core",
        target: "switch-server",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "20" },
        label: "10 Gbps",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e5",
        source: "switch-core",
        target: "switch-iot",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#8b5cf6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps", vlan: "30" },
        label: "1 Gbps",
        style: { stroke: "#8b5cf6", strokeWidth: 2.5 },
      },
      {
        id: "e6",
        source: "switch-office",
        target: "ap-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e7",
        source: "switch-office",
        target: "client-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e8",
        source: "switch-server",
        target: "server-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "10 Gbps" },
        label: "10 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e9",
        source: "switch-server",
        target: "server-2",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "10 Gbps" },
        label: "10 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e10",
        source: "switch-server",
        target: "nas-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "10 Gbps" },
        label: "10 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e11",
        source: "switch-iot",
        target: "camera-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
    ],
  },
  enterprise: {
    nodes: [
      {
        id: "cloud-1",
        type: "custom",
        position: { x: 700, y: 50 },
        data: {
          label: "Internet/Cloud",
          type: "cloud",
          status: "online",
        },
      },
      {
        id: "firewall-1",
        type: "custom",
        position: { x: 450, y: 250 },
        data: {
          label: "Primary Firewall",
          type: "firewall",
          status: "online",
          ipAddress: "10.0.0.1",
        },
      },
      {
        id: "firewall-2",
        type: "custom",
        position: { x: 950, y: 250 },
        data: {
          label: "Secondary Firewall",
          type: "firewall",
          status: "online",
          ipAddress: "10.0.0.2",
        },
      },
      {
        id: "router-core-1",
        type: "custom",
        position: { x: 450, y: 450 },
        data: {
          label: "Core Router 1",
          type: "router",
          status: "online",
          ipAddress: "10.0.1.1",
        },
      },
      {
        id: "router-core-2",
        type: "custom",
        position: { x: 950, y: 450 },
        data: {
          label: "Core Router 2",
          type: "router",
          status: "online",
          ipAddress: "10.0.1.2",
        },
      },
      {
        id: "switch-core-1",
        type: "custom",
        position: { x: 450, y: 650 },
        data: {
          label: "Core Switch 1",
          type: "switch",
          status: "online",
          ipAddress: "10.0.2.1",
        },
      },
      {
        id: "switch-core-2",
        type: "custom",
        position: { x: 950, y: 650 },
        data: {
          label: "Core Switch 2",
          type: "switch",
          status: "online",
          ipAddress: "10.0.2.2",
        },
      },
      {
        id: "switch-dmz",
        type: "custom",
        position: { x: 100, y: 850 },
        data: {
          label: "DMZ Switch",
          type: "switch",
          status: "online",
          ipAddress: "10.1.0.1",
          vlan: "100",
        },
      },
      {
        id: "switch-server",
        type: "custom",
        position: { x: 450, y: 850 },
        data: {
          label: "Server Switch",
          type: "switch",
          status: "online",
          ipAddress: "10.2.0.1",
          vlan: "200",
        },
      },
      {
        id: "switch-office",
        type: "custom",
        position: { x: 800, y: 850 },
        data: {
          label: "Office Switch",
          type: "switch",
          status: "online",
          ipAddress: "10.3.0.1",
          vlan: "300",
        },
      },
      {
        id: "switch-iot",
        type: "custom",
        position: { x: 1150, y: 850 },
        data: {
          label: "IoT Switch",
          type: "switch",
          status: "online",
          ipAddress: "10.4.0.1",
          vlan: "400",
        },
      },
      {
        id: "server-web",
        type: "custom",
        position: { x: 50, y: 1050 },
        data: {
          label: "Web Server",
          type: "server",
          status: "online",
          ipAddress: "10.1.0.10",
        },
      },
      {
        id: "server-mail",
        type: "custom",
        position: { x: 200, y: 1050 },
        data: {
          label: "Mail Server",
          type: "server",
          status: "online",
          ipAddress: "10.1.0.11",
        },
      },
      {
        id: "server-app",
        type: "custom",
        position: { x: 350, y: 1050 },
        data: {
          label: "App Server 1",
          type: "server",
          status: "online",
          ipAddress: "10.2.0.10",
        },
      },
      {
        id: "server-app2",
        type: "custom",
        position: { x: 500, y: 1050 },
        data: {
          label: "App Server 2",
          type: "server",
          status: "online",
          ipAddress: "10.2.0.11",
        },
      },
      {
        id: "server-db",
        type: "custom",
        position: { x: 650, y: 1050 },
        data: {
          label: "Database Cluster",
          type: "server",
          status: "online",
          ipAddress: "10.2.0.20",
        },
      },
      {
        id: "nas-1",
        type: "custom",
        position: { x: 800, y: 1050 },
        data: {
          label: "Storage Array",
          type: "nas",
          status: "online",
          ipAddress: "10.2.0.30",
        },
      },
      {
        id: "ap-1",
        type: "custom",
        position: { x: 950, y: 1050 },
        data: {
          label: "Office WiFi",
          type: "ap",
          status: "online",
          ipAddress: "10.3.0.10",
        },
      },
      {
        id: "camera-1",
        type: "custom",
        position: { x: 1250, y: 1050 },
        data: {
          label: "IP Camera",
          type: "camera",
          status: "online",
          ipAddress: "10.4.0.10",
        },
      },
    ],
    edges: [
      // Cloud to Firewalls
      {
        id: "e1",
        source: "cloud-1",
        target: "firewall-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "100 Gbps" },
        label: "100 Gbps",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e2",
        source: "cloud-1",
        target: "firewall-2",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "100 Gbps" },
        label: "100 Gbps",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      // Firewalls to Routers
      {
        id: "e3",
        source: "firewall-1",
        target: "router-core-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40 Gbps",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e4",
        source: "firewall-1",
        target: "router-core-2",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40 Gbps",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e5",
        source: "firewall-2",
        target: "router-core-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40 Gbps",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e6",
        source: "firewall-2",
        target: "router-core-2",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40 Gbps",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      // Routers to Core Switches
      {
        id: "e7",
        source: "router-core-1",
        target: "switch-core-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40 Gbps",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      {
        id: "e8",
        source: "router-core-2",
        target: "switch-core-2",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40 Gbps",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      // Core Switch Interconnect
      {
        id: "e9",
        source: "switch-core-1",
        target: "switch-core-2",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#ef4444" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps" },
        label: "40 Gbps",
        style: { stroke: "#ef4444", strokeWidth: 3.5 },
      },
      // Core Switches to Access Switches (redundant paths)
      {
        id: "e10",
        source: "switch-core-1",
        target: "switch-dmz",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#f97316" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "100" },
        label: "10 Gbps",
        style: { stroke: "#f97316", strokeWidth: 2.5 },
      },
      {
        id: "e11",
        source: "switch-core-1",
        target: "switch-server",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#22c55e" },
        data: { connectionType: "fiber", bandwidth: "40 Gbps", vlan: "200" },
        label: "40 Gbps",
        style: { stroke: "#22c55e", strokeWidth: 3.5 },
      },
      {
        id: "e12",
        source: "switch-core-1",
        target: "switch-office",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "300" },
        label: "10 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e13",
        source: "switch-core-2",
        target: "switch-iot",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#8b5cf6" },
        data: { connectionType: "fiber", bandwidth: "10 Gbps", vlan: "400" },
        label: "10 Gbps",
        style: { stroke: "#8b5cf6", strokeWidth: 2.5 },
      },
      // Access Switches to End Devices
      {
        id: "e14",
        source: "switch-dmz",
        target: "server-web",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "10 Gbps" },
        label: "10 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e15",
        source: "switch-dmz",
        target: "server-mail",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "10 Gbps" },
        label: "10 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e16",
        source: "switch-server",
        target: "server-app",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "10 Gbps" },
        label: "10 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e17",
        source: "switch-server",
        target: "server-app2",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "10 Gbps" },
        label: "10 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e18",
        source: "switch-server",
        target: "server-db",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "40 Gbps" },
        label: "40 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e19",
        source: "switch-server",
        target: "nas-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "40 Gbps" },
        label: "40 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e20",
        source: "switch-office",
        target: "ap-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
      {
        id: "e21",
        source: "switch-iot",
        target: "camera-1",
        type: "default",
        markerEnd: { type: MarkerType.ArrowClosed, color: "#3b82f6" },
        data: { connectionType: "ethernet", bandwidth: "1 Gbps" },
        label: "1 Gbps",
        style: { stroke: "#3b82f6", strokeWidth: 2.5 },
      },
    ],
  },
};
